"""add store settings

Revision ID: 3e0e9e420b00
Revises: 478c4e681973
Create Date: 2026-02-22 12:41:52.617718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e0e9e420b00'
down_revision = '478c4e681973'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_charge', sa.Float(), nullable=False),
    sa.Column('free_delivery_threshold', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_settings')
    # ### end Alembic commands ###
