"""add notif_type

Revision ID: 478c4e681973
Revises: 0001
Create Date: 2026-02-22 12:29:43.833286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478c4e681973'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_banner', sa.Column('notif_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_banner', 'notif_type')
    # ### end Alembic commands ###
