"""add stock_released

Revision ID: e019730bd97c
Revises: 3e0e9e420b00
Create Date: 2026-02-22 15:45:43.037052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e019730bd97c'
down_revision = '3e0e9e420b00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('stock_released', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'stock_released')
    # ### end Alembic commands ###
