import { createContext, useContext, useState } from "react";
import PropTypes from "prop-types";

const LanguageContext = createContext();

// Dictionary (UPDATED: same keys preserved, no emojis, slightly more professional, BN is fluent with light Banglish)
const translations = {
  en: {
    home: "Home",
    store: "Shop",
    new: "New Arrivals",
    connect: "Connect",
    admin: "Admin",
    dashboard: "Dashboard",
    orders: "Orders",
    products: "Products",
    categories: "Categories",
    c: "Settings",
    profile: "Profile",
    login: "Log In",
    logout: "Log Out",
    search_placeholder: "Search essentials...",
    back_home: "Back to Home",
    management: "Management",
    my_account: "My Account",
    delivery_notice: "Delivery available across Bangladesh",
    brand_tagline: "Pure taste from nature",
    category_management: "Category Management",
    search_categories: "Search categories...",
    add_category: "Add Category",
    category_name: "Category Name",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    edit_category: "Edit Category",
    create_category: "Create Category",
    create_category_btn: "Create Category",
    update_category: "Update Category",
    category_name_label: "Category Name",
    enter_category_name: "Please enter a category name",
    category_placeholder: "e.g. Rice, Spices, Beverages",
    cancel: "Cancel",
    delete_category_title: "Delete category?",
    delete_category_confirm:
      "This action cannot be undone. Products in this category may be affected.",
    category_updated: "Category updated successfully",
    category_created: "Category created successfully",
    category_deleted: "Category deleted",
    load_failed: "Failed to load categories",
    update_failed: "Update failed",
    creation_failed: "Creation failed",
    delete_failed: "Delete failed",
    of: "of",
    items: "items",
    dashboard_overview: "Dashboard Overview",
    analytics_center: "Analytics Center",
    analytics_desc: "Overview of store performance and required actions.",
    export: "Export",
    revenue: "Revenue",
    gross_income: "Gross income",
    total_profit: "Total profit",
    net_profit_desc: "Revenue minus recipe costs",
    profit_margin: "Profit margin",
    total_processed: "Total processed",
    revenue_trends: "Revenue trends",
    pending_actions: "Pending actions",
    order: "Order",
    all_caught_up: "No pending items",
    top_selling_products: "Top Selling Products",
    product: "Product",
    category: "Category",
    sold: "Sold",
    sales_by_category: "Sales by Category",
    peak_order_times: "Peak Order Times",
    regional_distribution: "Regional Distribution",
    sales_history: "Sales History",
    top_products: "Top Products",
    order_history: "Order History",
    filter_by_user: "Filter by User",
    payment_status: "Payment Status",
    refresh: "Refresh",
    customer: "Customer",
    date: "Date",
    status: "Status",
    status_new: "New",
    status_processing: "Processing",
    status_transit: "In Transit",
    status_delivered: "Delivered",
    payment: "Payment",
    paid: "Paid",
    unpaid: "Unpaid",
    marked_paid: "Marked as paid",
    marked_unpaid: "Marked as unpaid",
    status_updated: "Status updated",
    view_details: "View Details",
    delete_order_title: "Delete order?",
    delete_order_confirm: "This action cannot be undone.",
    order_details: "Order Details",
    name: "Name",
    email: "Email",
    phone: "Phone",
    address: "Address",
    no_notes: "No notes",
    error_parsing: "Parsing error",
    product_inventory: "Product Inventory",
    search_products: "Search products...",
    add_product: "Add Product",
    image_size_error: "Image must be smaller than 1MB",
    load_products_failed: "Failed to load products",
    select_valid_image: "Please select a valid image file",
    product_updated: "Product updated",
    product_created: "Product created",
    error_saving_product: "Error saving product",
    delete_product_title: "Delete product?",
    delete_product_confirm: "This action cannot be undone.",
    deleted_success: "Deleted successfully",
    ingredient_added: "Ingredient added",
    select_image_upload: "Please select at least one new image to upload",
    gallery_updated: "Gallery updated successfully",
    upload_failed: "Upload failed",
    main_image: "Main Image",
    stock: "Stock",
    gallery: "Gallery",
    recipe: "Recipe",
    edit_product: "Edit Product",
    new_product: "New Product",
    size_unit: "Size/Unit",
    size_placeholder: "e.g. Large, 500g",
    description: "Description",
    description_max_error: "Description cannot exceed 2000 characters",
    product_details_placeholder: "Product details...",
    upload_main_image: "Please upload the main product image",
    select_image_file: "Select Image File (Max 1MB)",
    mark_new_arrival: "Mark as New Arrival",
    save_product: "Save Product",
    item_name: "Item Name",
    qty: "Qty",
    cost: "Cost ($)",
    ingredient: "Ingredient",
    unit_cost: "Unit Cost",
    total: "Total",
    upload_images: "Upload Images",
    side_view: "Side View (Image 2)",
    detail_view: "Detail View (Image 3)",
    max_1mb: "Max 1MB",
    shopping_cart: "Shopping Cart",
    you_have: "You have",
    items_in_cart: "items in your cart",
    cart_empty_msg: "Your cart is currently empty",
    cart_is_empty: "Your cart is empty",
    looks_like_empty:
      "Looks like you have not added anything to your cart yet.",
    start_shopping: "Start Shopping",
    order_summary: "Order Summary",
    subtotal: "Subtotal",
    shipping: "Shipping",
    proceed_checkout: "Proceed to Checkout",
    continue_shopping: "Continue Shopping",
    checkout: "Checkout",
    complete_purchase: "Please complete your purchase details below.",
    shipping_info: "Shipping Information",
    full_name: "Full Name",
    email_optional: "Email (Optional)",
    phone_number: "Phone Number",
    full_address: "Full Address (House, Street, Area, City)",
    order_notes: "Order notes (Optional)",
    payment_method: "Payment Method",
    cash_on_delivery: "Cash on Delivery",
    digital_payment: "Digital Payment",
    coming_soon: "Coming Soon",
    your_order: "Your Order",
    confirm_order: "Confirm Order",
    login_required: "Login Required",
    login_required_msg: "You need to log in to place an order.",
    login_continue: "Log In & Continue",
    no_account: "Don't have an account?",
    register_here: "Register Here",
    order_placed: "Order placed successfully",
    place_order_failed: "Failed to place order",
    fill_required: "Please fill all required fields",
    invalid_credentials: "Invalid credentials",
    logged_in: "Logged in successfully",
    password: "Password",
    founder_ceo: "Founder & CEO",
    ops_director: "Operations Director",
    head_sourcing: "Head of Sourcing",
    quote_founder: "Our goal is simple: purity from the soil to your table.",
    quote_ops: "Every delivery carries our promise of quality.",
    quote_sourcing: "I personally visit farms to select the best for you.",
    tl_title_1: "Where It Began",
    tl_desc_1:
      "Started as a small community effort to source chemical-free vegetables for friends and family during the pandemic.",
    tl_title_2: "Growing Trust",
    tl_desc_2:
      "Expanded to a small warehouse in Badda and partnered with local farmers who share our organic vision.",
    tl_title_3: "Swadesh Food Online",
    tl_desc_3:
      "Launched our digital platform to make healthy, organic food accessible to households in Dhaka.",
    connect_title_1: "Rooted in ",
    connect_title_2: "Trust",
    connect_subtitle:
      "We are more than a store; we are a community working to bring the authentic taste of Bangladesh to your table.",
    our_mission_tag: "Our Mission",
    mission_title: "Why We Do What We Do",
    mission_p1_start:
      "In a world full of processed options, finding food that supports your wellbeing can be difficult. ",
    mission_p1_end:
      "was created to make safe, chemical-free, and responsibly sourced food easier to access.",
    mission_p2:
      "Our mission is to connect rural farmers with urban families who value quality. Every product reflects purity, ethics, and care.",
    organic_100: "100% Organic",
    farmer_first: "Farmer First",
    farm_quote: "Directly sourced from North Bengal fields.",
    team_title: "Meet the Team",
    team_subtitle: "Real people, real commitment.",
    timeline_title: "Our Journey So Far",
    call_us: "Call Us",
    email_us: "Email Us",
    direct_farm: "Direct from Farm",
    organic: "Organic",
    living: "Lifestyle",
    hero_subtitle:
      "Nourish your family with trusted ingredients. No chemicals, just careful sourcing.",
    our_story: "Our Story",
    browse_aisles: "Browse Collections",
    aisles_subtitle: "Everything you need for a healthy kitchen",
    customer_favorites: "Customer Favorites",
    weekly_harvest: "Weekly Harvest",
    view_all: "View All",
    view_all_products: "View All Products",
    just_landed: "Just In",
    fresh_arrivals: "Fresh Arrivals",
    fresh_subtitle: "Explore the season’s newest selections.",
    discover_more: "Discover More",
    trust_p1: "From our soil",
    trust_p2: "to your table.",
    trust_subtitle:
      "We partner directly with sustainable farmers to bring you produce that is 100% organic and responsibly sourced. It's a promise you can rely on.",
    our_mission: "Our Mission",
    welcome_back: "Welcome Back",
    login_subtitle: "Log in to access your account and order history",
    sign_in: "Sign In",
    signing_in: "Signing in...",
    fill_all_fields: "Please fill in all fields",
    login_failed: "Login failed. Please check your credentials.",
    logout_success: "Logged out successfully",
    create_account: "Create Account",
    fresh_in: "Fresh In",
    new_arrivals_title: "New Arrivals",
    new_arrivals_desc:
      "Explore our latest organic additions, selected for quality and freshness.",
    coming_soon_title: "New products coming soon",
    restocking_msg:
      "We are restocking with fresh goods. Please check back later.",
    browse_main_store: "Browse Main Store",
    view_more_arrivals: "View More Arrivals",
    change_password: "Change Password",
    order_id: "Order ID",
    details: "Details",
    action: "Action",
    view: "View",
    recipient: "Recipient",
    items_ordered: "Items Ordered",
    cancel_order: "Cancel Order",
    yes_cancel: "Yes, Cancel Order",
    cancel_confirm_msg:
      "Are you sure you want to cancel this order? This action cannot be undone.",
    current_password: "Current Password",
    new_password: "New Password",
    confirm_password: "Confirm New Password",
    update_password: "Update Password",
    order_cancelled: "Order cancelled successfully",
    passwords_mismatch: "Passwords do not match",
    password_updated: "Password updated successfully",
    join_us: "Join us for authentic and healthy food",
    username: "Username",
    register: "Register",
    creating_account: "Creating account...",
    already_have_account: "Already have an account?",
    log_in: "Log In",
    reg_failed: "Registration failed. Please try again.",
    search_results: "Search Results",
    searching: "Searching our inventory...",
    no_results: "No products found",
    no_match_1: "We could not find anything matching",
    no_match_2: "Try checking for typos or use a more general term.",
    browse_all: "Browse All Products",
    found: "Found",
    new_arrival: "New Arrival",
    only_left: "Only {{count}} left",
    product_desc_default:
      "Premium organic selection, responsibly sourced and delivered fresh to your doorstep.",
    select_size: "Select Size",
    buy_it_now: "Buy It Now",
    delivery: "Delivery",
    delivery_time: "2–3 days within Dhaka",
    might_like: "You Might Also Like",
    load_more: "Load More",
    added_to_cart: "Added to cart",
    the_store: "The Store",
    collection: "Collection",
    store_desc:
      "Browse our full range of organic, farm-fresh products delivered straight to your door.",
    filter_by: "Filter By",
    size: "Size",
    sort_price: "Sort Price",
    low_to_high: "Low to High",
    high_to_low: "High to Low",
    reset: "Reset",
    no_products_found: "No Products Found",
    adjust_filters: "Try adjusting your filters or search criteria.",
    clear_filters: "Clear All Filters",
    load_more_products: "Load More Products",
    new_badge: "New",
    price_label: "Price",
    add_to_cart: "Add to Cart",
    options: "Options",
    sign_out_confirmation: "Are you sure you want to sign out?",
    quick_links: "Quick Links",
    contact_us: "Contact Us",
    visit_us: "Visit Us",
    all_rights_reserved: "All rights reserved.",
    privacy_policy: "Privacy Policy",
    terms_of_service: "Terms of Service",
    copy_success: "Copied to clipboard",
    copy_fail: "Failed to copy",
    click_to_copy: "Click to copy",
    dark_mode: "Dark Mode",
    light_mode: "Light Mode",
    shipping_cost: "Shipping",
    order_status_new: "New",
    order_status_processing: "Processing",
    order_status_transit: "In Transit",
    order_status_delivered: "Delivered",
    order_status_cancelled: "Cancelled",
    brand_name: "Swadesh Food",
    dashboard_report: "Dashboard Report",
    out_of_stock: "Out of stock",
  },

  bn: {
    home: "হোম",
    store: "শপ",
    new: "নতুন এসেছে",
    connect: "কানেক্ট",
    admin: "অ্যাডমিন",
    dashboard: "ড্যাশবোর্ড",
    orders: "অর্ডারস",
    products: "প্রোডাক্টস",
    categories: "ক্যাটাগরি",
    settings: "সেটিংস",
    profile: "প্রোফাইল",
    login: "লগইন",
    logout: "লগআউট",
    search_placeholder: "প্রয়োজনীয় জিনিস সার্চ করুন...",
    back_home: "হোমে ফিরে যান",
    management: "ম্যানেজমেন্ট",
    my_account: "আমার অ্যাকাউন্ট",
    delivery_notice: "সারা বাংলাদেশে ডেলিভারি",
    brand_tagline: "খাঁটি স্বাদ, প্রকৃতি থেকে",
    category_management: "ক্যাটাগরি ম্যানেজমেন্ট",
    search_categories: "ক্যাটাগরি সার্চ করুন...",
    add_category: "নতুন ক্যাটাগরি যোগ করুন",
    category_name: "ক্যাটাগরির নাম",
    actions: "অ্যাকশন",
    edit: "এডিট",
    delete: "ডিলিট",
    edit_category: "ক্যাটাগরি এডিট",
    create_category: "নতুন ক্যাটাগরি তৈরি করুন",
    create_category_btn: "ক্যাটাগরি তৈরি করুন",
    update_category: "ক্যাটাগরি আপডেট",
    category_name_label: "ক্যাটাগরির নাম",
    enter_category_name: "দয়া করে ক্যাটাগরির নাম লিখুন",
    category_placeholder: "যেমন: চাল, মসলা, পানীয়",
    cancel: "ক্যান্সেল",
    delete_category_title: "ক্যাটাগরি ডিলিট করবেন?",
    delete_category_confirm:
      "এটা আনডু করা যাবে না। এই ক্যাটাগরির প্রোডাক্টগুলো প্রভাবিত হতে পারে।",
    category_updated: "ক্যাটাগরি আপডেট হয়েছে",
    category_created: "ক্যাটাগরি তৈরি হয়েছে",
    category_deleted: "ক্যাটাগরি ডিলিট হয়েছে",
    load_failed: "ক্যাটাগরি লোড করা যায়নি",
    update_failed: "আপডেট করা যায়নি",
    creation_failed: "তৈরি করা যায়নি",
    delete_failed: "ডিলিট করা যায়নি",
    of: "এর মধ্যে",
    items: "টি আইটেম",
    dashboard_overview: "ড্যাশবোর্ড ওভারভিউ",
    analytics_center: "অ্যানালিটিক্স সেন্টার",
    analytics_desc: "স্টোর পারফরম্যান্স এবং প্রয়োজনীয় কাজের সারাংশ।",
    export: "এক্সপোর্ট",
    revenue: "রেভিনিউ",
    gross_income: "মোট ইনকাম",
    total_profit: "মোট প্রফিট",
    net_profit_desc: "রেভিনিউ থেকে রেসিপি কস্ট বাদে",
    profit_margin: "প্রফিট মার্জিন",
    total_processed: "মোট প্রসেসড",
    revenue_trends: "রেভিনিউ ট্রেন্ডস",
    pending_actions: "পেন্ডিং কাজ",
    order: "অর্ডার",
    all_caught_up: "এখন কিছু পেন্ডিং নেই",
    top_selling_products: "টপ সেলিং প্রোডাক্টস",
    product: "প্রোডাক্ট",
    category: "ক্যাটাগরি",
    sold: "বিক্রি",
    sales_by_category: "ক্যাটাগরি অনুযায়ী সেলস",
    peak_order_times: "অর্ডারের পিক টাইম",
    regional_distribution: "আঞ্চলিক ডিস্ট্রিবিউশন",
    sales_history: "সেলস হিস্ট্রি",
    top_products: "টপ প্রোডাক্টস",
    order_history: "অর্ডার হিস্ট্রি",
    filter_by_user: "ইউজার অনুযায়ী ফিল্টার",
    payment_status: "পেমেন্ট স্ট্যাটাস",
    refresh: "রিফ্রেশ",
    customer: "কাস্টমার",
    date: "তারিখ",
    status: "স্ট্যাটাস",
    status_new: "নতুন",
    status_processing: "প্রসেসিং",
    status_transit: "ইন ট্রানজিট",
    status_delivered: "ডেলিভারড",
    payment: "পেমেন্ট",
    paid: "পেইড",
    unpaid: "আনপেইড",
    marked_paid: "পেইড হিসেবে মার্ক হয়েছে",
    marked_unpaid: "আনপেইড হিসেবে মার্ক হয়েছে",
    status_updated: "স্ট্যাটাস আপডেট হয়েছে",
    view_details: "ডিটেইলস দেখুন",
    delete_order_title: "অর্ডার ডিলিট করবেন?",
    delete_order_confirm: "এটা আনডু করা যাবে না।",
    order_details: "অর্ডার ডিটেইলস",
    name: "নাম",
    email: "ইমেইল",
    phone: "ফোন",
    address: "ঠিকানা",
    no_notes: "কোনো নোট নেই",
    error_parsing: "ডাটা পার্সিং সমস্যা",
    product_inventory: "প্রোডাক্ট ইনভেন্টরি",
    search_products: "প্রোডাক্ট সার্চ করুন...",
    add_product: "প্রোডাক্ট যোগ করুন",
    image_size_error: "ইমেজ ১MB এর কম হতে হবে",
    load_products_failed: "প্রোডাক্ট লোড করা যায়নি",
    select_valid_image: "সঠিক ইমেজ ফাইল সিলেক্ট করুন",
    product_updated: "প্রোডাক্ট আপডেট হয়েছে",
    product_created: "প্রোডাক্ট তৈরি হয়েছে",
    error_saving_product: "প্রোডাক্ট সেভ করা যায়নি",
    delete_product_title: "প্রোডাক্ট ডিলিট করবেন?",
    delete_product_confirm: "এটা আনডু করা যাবে না।",
    deleted_success: "সফলভাবে ডিলিট হয়েছে",
    ingredient_added: "ইনগ্রেডিয়েন্ট যোগ হয়েছে",
    select_image_upload: "অন্তত একটি নতুন ইমেজ সিলেক্ট করুন",
    gallery_updated: "গ্যালারি আপডেট হয়েছে",
    upload_failed: "আপলোড ফেইলড",
    main_image: "মেইন ইমেজ",
    stock: "স্টক",
    gallery: "গ্যালারি",
    recipe: "রেসিপি",
    edit_product: "প্রোডাক্ট এডিট",
    new_product: "নতুন প্রোডাক্ট",
    size_unit: "সাইজ/ইউনিট",
    size_placeholder: "যেমন: ৫০০ গ্রাম, ১ কেজি",
    description: "বিবরণ",
    description_max_error: "বিবরণ ২০০০ অক্ষরের বেশি হতে পারবে না",
    product_details_placeholder: "প্রোডাক্টের বিস্তারিত...",
    upload_main_image: "মেইন প্রোডাক্ট ইমেজ আপলোড করুন",
    select_image_file: "ইমেজ ফাইল সিলেক্ট করুন (ম্যাক্স ১MB)",
    mark_new_arrival: "নিউ অ্যারাইভাল হিসেবে মার্ক করুন",
    save_product: "প্রোডাক্ট সেভ করুন",
    item_name: "আইটেমের নাম",
    qty: "পরিমাণ",
    cost: "কস্ট ($)",
    ingredient: "ইনগ্রেডিয়েন্ট",
    unit_cost: "ইউনিট কস্ট",
    total: "মোট",
    upload_images: "ইমেজ আপলোড",
    side_view: "সাইড ভিউ (ইমেজ ২)",
    detail_view: "ডিটেইল ভিউ (ইমেজ ৩)",
    max_1mb: "ম্যাক্স ১MB",
    shopping_cart: "শপিং কার্ট",
    you_have: "আপনার কার্টে",
    items_in_cart: "টি আইটেম আছে",
    cart_empty_msg: "আপনার কার্ট এখন খালি",
    cart_is_empty: "আপনার কার্ট খালি",
    looks_like_empty: "এখনো কার্টে কিছু যোগ করেননি।",
    start_shopping: "শপিং শুরু করুন",
    order_summary: "অর্ডার সামারি",
    subtotal: "সাবটোটাল",
    shipping: "শিপিং",
    proceed_checkout: "চেকআউটে যান",
    continue_shopping: "আরও শপিং করুন",
    checkout: "চেকআউট",
    complete_purchase: "নিচে অর্ডারের তথ্য পূরণ করুন।",
    shipping_info: "শিপিং ইনফরমেশন",
    full_name: "পূর্ণ নাম",
    email_optional: "ইমেইল (ঐচ্ছিক)",
    phone_number: "ফোন নম্বর",
    full_address: "পূর্ণ ঠিকানা (বাসা, রোড, এলাকা, শহর)",
    order_notes: "অর্ডার নোট (ঐচ্ছিক)",
    payment_method: "পেমেন্ট মেথড",
    cash_on_delivery: "ক্যাশ অন ডেলিভারি",
    digital_payment: "ডিজিটাল পেমেন্ট",
    coming_soon: "শিগগিরই আসছে",
    your_order: "আপনার অর্ডার",
    confirm_order: "অর্ডার কনফার্ম করুন",
    login_required: "লগইন প্রয়োজন",
    login_required_msg: "অর্ডার করতে হলে আগে লগইন করতে হবে।",
    login_continue: "লগইন করে কন্টিনিউ করুন",
    no_account: "অ্যাকাউন্ট নেই?",
    register_here: "রেজিস্টার করুন",
    order_placed: "অর্ডার সফলভাবে হয়েছে",
    place_order_failed: "অর্ডার প্লেস করা যায়নি",
    fill_required: "সব প্রয়োজনীয় ফিল্ড পূরণ করুন",
    invalid_credentials: "ভুল তথ্য দেওয়া হয়েছে",
    logged_in: "লগইন সফল",
    password: "পাসওয়ার্ড",
    founder_ceo: "প্রতিষ্ঠাতা ও সিইও",
    ops_director: "অপারেশন ডিরেক্টর",
    head_sourcing: "হেড অফ সোর্সিং",
    quote_founder: "আমাদের লক্ষ্য সহজ: খাঁটি খাবার সবার জন্য।",
    quote_ops: "প্রতিটি ডেলিভারি মানের প্রতিশ্রুতি বজায় রাখে।",
    quote_sourcing: "সেরা পণ্য বাছাই করতে আমরা সরাসরি উৎসে যাই।",
    tl_title_1: "শুরুর কথা",
    tl_desc_1:
      "মহামারীর সময় ফ্যামিলি ও ফ্রেন্ডদের জন্য কেমিক্যাল-মুক্ত খাবার সংগ্রহের উদ্যোগ হিসেবে শুরু হয়েছিল।",
    tl_title_2: "বিশ্বাস তৈরি",
    tl_desc_2:
      "বাড্ডায় ছোট ওয়্যারহাউস থেকে শুরু করে, আমাদের ভিশনে বিশ্বাসী স্থানীয় কৃষকদের সাথে কাজ করছি।",
    tl_title_3: "স্বদেশ ফুড অনলাইন",
    tl_desc_3:
      "ঢাকার ঘরে ঘরে অর্গানিক খাবার পৌঁছে দিতে আমাদের অনলাইন প্ল্যাটফর্ম চালু হয়েছে।",
    connect_title_1: "ভিত্তি ",
    connect_title_2: "বিশ্বাস",
    connect_subtitle:
      "আমরা শুধু একটি স্টোর নই; কৃষক ও পরিবারের মধ্যে একটি বিশ্বাসের সংযোগ তৈরি করাই আমাদের লক্ষ্য।",
    our_mission_tag: "আমাদের মিশন",
    mission_title: "আমরা কেন কাজ করি",
    mission_p1_start:
      "প্রসেসড খাবারের ভিড়ে নিরাপদ খাবার পাওয়া কঠিন। সেই চাহিদা পূরণ করতেই ",
    mission_p1_end: "শুরু হয়েছে।",
    mission_p2:
      "আমাদের লক্ষ্য হলো গ্রামীণ কৃষক আর শহুরে পরিবারের মধ্যে সংযোগ তৈরি করা—যাতে আপনি পান নিরাপদ, মানসম্মত খাবার।",
    organic_100: "১০০% অর্গানিক",
    farmer_first: "কৃষক আগে",
    farm_quote: "সরাসরি উত্তরবঙ্গের মাঠ থেকে।",
    team_title: "স্বদেশ টিম",
    team_subtitle: "মান আর স্বচ্ছতাই আমাদের অগ্রাধিকার।",
    timeline_title: "আমাদের জার্নি",
    call_us: "কল করুন",
    email_us: "ইমেইল করুন",
    direct_farm: "সরাসরি খামার থেকে",
    organic: "অর্গানিক",
    living: "লাইফস্টাইল",
    hero_subtitle:
      "বিশ্বাসযোগ্য উপাদানে আপনার পরিবারকে রাখুন ভালো। কোনো কেমিক্যাল নয়, শুধু দায়িত্বশীল সোর্সিং।",
    our_story: "আমাদের গল্প",
    browse_aisles: "কালেকশন দেখুন",
    aisles_subtitle: "হেলদি কিচেনের জন্য প্রয়োজনীয় সবকিছু",
    customer_favorites: "কাস্টমার ফেভারিট",
    weekly_harvest: "সাপ্তাহিক সংগ্রহ",
    view_all: "সব দেখুন",
    view_all_products: "সব প্রোডাক্ট দেখুন",
    just_landed: "সদ্য এসেছে",
    fresh_arrivals: "ফ্রেশ অ্যারাইভালস",
    fresh_subtitle: "মৌসুমের নতুন পণ্যগুলো দেখুন।",
    discover_more: "আরও জানুন",
    trust_p1: "মাটি থেকে",
    trust_p2: "আপনার টেবিলে।",
    trust_subtitle:
      "আমরা সরাসরি টেকসই কৃষকদের সাথে কাজ করি, যাতে আপনি পান অর্গানিক এবং দায়িত্বশীলভাবে সোর্স করা পণ্য।",
    our_mission: "আমাদের মিশন",
    welcome_back: "স্বাগতম",
    login_subtitle: "আপনার অ্যাকাউন্ট এবং অর্ডার হিস্ট্রি দেখতে লগইন করুন",
    sign_in: "সাইন ইন",
    signing_in: "সাইন ইন হচ্ছে...",
    fill_all_fields: "সবগুলো ফিল্ড পূরণ করুন",
    login_failed: "লগইন হয়নি। দয়া করে তথ্য যাচাই করুন।",
    logout_success: "সফলভাবে লগআউট হয়েছে",
    create_account: "অ্যাকাউন্ট খুলুন",
    fresh_in: "ফ্রেশ ইন",
    new_arrivals_title: "নিউ অ্যারাইভালস",
    new_arrivals_desc:
      "আমাদের নতুন অর্গানিক অ্যাডিশনগুলো দেখুন—কোয়ালিটি ও ফ্রেশनेस মাথায় রেখে বাছাই করা।",
    coming_soon_title: "নতুন প্রোডাক্ট শিগগিরই আসছে",
    restocking_msg: "নতুন স্টক আসছে। কিছুক্ষণ পর আবার দেখুন।",
    browse_main_store: "মেইন স্টোর দেখুন",
    view_more_arrivals: "আরও দেখুন",
    change_password: "পাসওয়ার্ড পরিবর্তন",
    order_id: "অর্ডার আইডি",
    details: "ডিটেইলস",
    action: "অ্যাকশন",
    view: "দেখুন",
    recipient: "প্রাপক",
    items_ordered: "অর্ডার করা আইটেম",
    cancel_order: "অর্ডার ক্যান্সেল",
    yes_cancel: "হ্যাঁ, ক্যান্সেল করুন",
    cancel_confirm_msg:
      "আপনি কি নিশ্চিতভাবে অর্ডারটি ক্যান্সেল করবেন? এটা আনডু করা যাবে না।",
    current_password: "বর্তমান পাসওয়ার্ড",
    new_password: "নতুন পাসওয়ার্ড",
    confirm_password: "নতুন পাসওয়ার্ড কনফার্ম করুন",
    update_password: "পাসওয়ার্ড আপডেট করুন",
    order_cancelled: "অর্ডার ক্যান্সেল হয়েছে",
    passwords_mismatch: "পাসওয়ার্ড মিলছে না",
    password_updated: "পাসওয়ার্ড আপডেট হয়েছে",
    join_us: "খাঁটি ও হেলদি খাবারের জন্য আমাদের সাথে থাকুন",
    username: "ইউজারনেম",
    register: "রেজিস্টার",
    creating_account: "অ্যাকাউন্ট তৈরি হচ্ছে...",
    already_have_account: "অলরেডি অ্যাকাউন্ট আছে?",
    log_in: "লগইন",
    reg_failed: "রেজিস্ট্রেশন হয়নি। আবার চেষ্টা করুন।",
    search_results: "সার্চ রেজাল্ট",
    searching: "ইনভেন্টরি সার্চ হচ্ছে...",
    no_results: "কোনো প্রোডাক্ট পাওয়া যায়নি",
    no_match_1: "ম্যাচিং কিছু পাওয়া যায়নি",
    no_match_2: "বানান চেক করুন অথবা অন্য শব্দ দিয়ে সার্চ করুন।",
    browse_all: "সব প্রোডাক্ট দেখুন",
    found: "পাওয়া গেছে",
    new_arrival: "নিউ অ্যারাইভাল",
    only_left: "মাত্র {{count}}টি বাকি",
    product_desc_default:
      "প্রিমিয়াম অর্গানিক সিলেকশন—দায়িত্বশীলভাবে সোর্স করা এবং সতেজভাবে ডেলিভারি করা হয়।",
    select_size: "সাইজ সিলেক্ট করুন",
    buy_it_now: "এখনই কিনুন",
    delivery: "ডেলিভারি",
    delivery_time: "ঢাকার ভেতরে ২–৩ দিন",
    might_like: "আপনার পছন্দ হতে পারে",
    load_more: "আরও দেখুন",
    added_to_cart: "কার্টে যোগ হয়েছে",
    the_store: "স্টোর",
    collection: "কালেকশন",
    store_desc:
      "অর্গানিক এবং ফার্ম-ফ্রেশ প্রোডাক্টের পুরো কালেকশন দেখুন—ডোরস্টেপ ডেলিভারিসহ।",
    filter_by: "ফিল্টার",
    size: "সাইজ",
    sort_price: "প্রাইস অনুযায়ী",
    low_to_high: "কম থেকে বেশি",
    high_to_low: "বেশি থেকে কম",
    reset: "রিসেট",
    no_products_found: "কোনো প্রোডাক্ট পাওয়া যায়নি",
    adjust_filters: "ফিল্টার বা সার্চ বদলে চেষ্টা করুন।",
    clear_filters: "সব ফিল্টার ক্লিয়ার করুন",
    load_more_products: "আরও প্রোডাক্ট দেখুন",
    new_badge: "নতুন",
    price_label: "প্রাইস",
    add_to_cart: "কার্টে যোগ করুন",
    options: "অপশনস",
    sign_out_confirmation: "আপনি কি নিশ্চিতভাবে সাইন আউট করবেন?",
    quick_links: "কুইক লিঙ্কস",
    contact_us: "কন্টাক্ট করুন",
    visit_us: "ভিজিট করুন",
    all_rights_reserved: "All rights reserved.",
    privacy_policy: "প্রাইভেসি পলিসি",
    terms_of_service: "টার্মস অফ সার্ভিস",
    copy_success: "কপি হয়েছে",
    copy_fail: "কপি করা যায়নি",
    click_to_copy: "কপি করতে ক্লিক করুন",
    dark_mode: "ডার্ক মোড",
    light_mode: "লাইট মোড",
    shipping_cost: "শিপিং",
    order_status_new: "নতুন",
    order_status_processing: "প্রসেসিং",
    order_status_transit: "ইন ট্রানজিট",
    order_status_delivered: "ডেলিভারড",
    order_status_cancelled: "ক্যান্সেলড",
    brand_name: "স্বদেশ ফুড",
    dashboard_report: "ড্যাশবোর্ড রিপোর্ট",
    out_of_stock: "স্টক নেই",
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(
    localStorage.getItem("lang") || "en",
  );

  const switchLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem("lang", lang);
  };

  // Helper to get text
  const t = (key, params = {}) => {
    let text = translations[language][key] || key;

    // Simple interpolation for {{key}}
    Object.keys(params).forEach((paramKey) => {
      text = text.replace(`{{${paramKey}}}`, params[paramKey]);
    });

    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, switchLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

LanguageProvider.propTypes = {
  children: PropTypes.node,
};

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => useContext(LanguageContext);
