import { createContext, useContext, useState } from "react";
import PropTypes from "prop-types";

const LanguageContext = createContext();

// Dictionary
const translations = {
  en: {
    home: "Home",
    store: "Store",
    new: "New",
    connect: "Connect",
    admin: "Admin",
    dashboard: "Dashboard",
    orders: "Orders",
    products: "Products",
    categories: "Categories",
    profile: "Profile",
    login: "Login",
    logout: "Logout",
    search_placeholder: "Search essentials...",
    back_home: "Back to Home",
    management: "Management",
    my_account: "My Account",
    delivery_notice: "We deliver across Bangladesh!",
    brand_tagline: "Taste the Purity of Nature.",
    category_management: "Category Management",
    search_categories: "Search categories...",
    add_category: "Add New Category",
    category_name: "Category Name",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    edit_category: "Edit Category",
    create_category: "Create New Category",
    create_category_btn: "Create Category",
    update_category: "Update Category",
    category_name_label: "Category Name",
    enter_category_name: "Please enter a category name",
    category_placeholder: "e.g. Rice, Spices, Beverages",
    cancel: "Cancel",
    delete_category_title: "Delete Category?",
    delete_category_confirm:
      "This action cannot be undone. Products in this category might be affected.",
    category_updated: "Category updated successfully",
    category_created: "Category created successfully",
    category_deleted: "Category deleted",
    load_failed: "Failed to load categories",
    update_failed: "Update failed",
    creation_failed: "Creation failed",
    delete_failed: "Delete failed",
    of: "of",
    items: "items",
    dashboard_overview: "Dashboard Overview",
    analytics_center: "Analytics Center",
    analytics_desc: "Overview of store performance and required actions.",
    export: "Export",
    revenue: "Revenue",
    gross_income: "Gross income",
    total_profit: "Total Profit",
    net_profit_desc: "Revenue - Recipe Costs",
    profit_margin: "Profit Margin",
    total_processed: "Total processed",
    revenue_trends: "Revenue Trends",
    pending_actions: "Pending Actions",
    order: "Order",
    all_caught_up: "All caught up!",
    top_selling_products: "Top Selling Products",
    product: "Product",
    category: "Category",
    sold: "Sold",
    sales_by_category: "Sales by Category",
    peak_order_times: "Peak Order Times",
    regional_distribution: "Regional Distribution",
    sales_history: "Sales History",
    top_products: "Top Products",
    order_history: "Order History",
    filter_by_user: "Filter by User",
    payment_status: "Payment Status",
    refresh: "Refresh",
    customer: "Customer",
    date: "Date",
    status: "Status",
    status_new: "New",
    status_processing: "Processing",
    status_transit: "In Transit",
    status_delivered: "Delivered",
    payment: "Payment",
    paid: "Paid",
    unpaid: "Unpaid",
    marked_paid: "Marked as Paid",
    marked_unpaid: "Marked as Unpaid",
    status_updated: "Status Updated",
    view_details: "View Details",
    delete_order_title: "Delete Order?",
    delete_order_confirm: "This action cannot be undone.",
    order_details: "Order Details",
    name: "Name",
    email: "Email",
    phone: "Phone",
    address: "Address",
    no_notes: "No notes",
    error_parsing: "Error parsing",
    product_inventory: "Product Inventory",
    search_products: "Search products...",
    add_product: "Add Product",
    image_size_error: "Image must be smaller than 1MB!",
    load_products_failed: "Failed to load products",
    select_valid_image: "Please select a valid image file",
    product_updated: "Product Updated",
    product_created: "Product Created",
    error_saving_product: "Error saving product",
    delete_product_title: "Delete Product?",
    delete_product_confirm: "This cannot be undone.",
    deleted_success: "Deleted successfully",
    ingredient_added: "Ingredient added",
    select_image_upload: "Please select at least one new image to upload",
    gallery_updated: "Gallery updated successfully!",
    upload_failed: "Upload failed",
    main_image: "Main Image",
    stock: "Stock",
    gallery: "Gallery",
    recipe: "Recipe",
    edit_product: "Edit Product",
    new_product: "New Product",
    size_unit: "Size/Unit",
    size_placeholder: "e.g. Large, 500g",
    description: "Description",
    description_max_error: "Description cannot exceed 2000 characters",
    product_details_placeholder: "Product details...",
    upload_main_image: "Please upload the main product image",
    select_image_file: "Select Image File (Max 1MB)",
    mark_new_arrival: "Mark as New Arrival",
    save_product: "Save Product",
    item_name: "Item Name",
    qty: "Qty",
    cost: "Cost ($)",
    ingredient: "Ingredient",
    unit_cost: "Unit Cost",
    total: "Total",
    upload_images: "Upload Images",
    side_view: "Side View (Image 2)",
    detail_view: "Detail View (Image 3)",
    max_1mb: "Max 1MB",
    shopping_cart: "Shopping Cart",
    you_have: "You have",
    items_in_cart: "items in your cart",
    cart_empty_msg: "Your cart is currently empty",
    cart_is_empty: "Your cart is empty",
    looks_like_empty: "Looks like you haven't added anything to your cart yet.",
    start_shopping: "Start Shopping",
    order_summary: "Order Summary",
    subtotal: "Subtotal",
    shipping: "Shipping",
    proceed_checkout: "Proceed to Checkout",
    continue_shopping: "Continue Shopping",
    checkout: "Checkout",
    complete_purchase: "Complete your purchase details below.",
    shipping_info: "Shipping Information",
    full_name: "Full Name",
    email_optional: "Email (Optional)",
    phone_number: "Phone Number",
    full_address: "Full Address (House, Street, Area, City)",
    order_notes: "Order notes (Optional)",
    payment_method: "Payment Method",
    cash_on_delivery: "Cash on Delivery",
    digital_payment: "Digital Payment",
    coming_soon: "Coming Soon",
    your_order: "Your Order",
    confirm_order: "Confirm Order",
    login_required: "Login Required",
    login_required_msg: "You need to log in to place an order.",
    login_continue: "Login & Continue",
    no_account: "Don't have an account?",
    register_here: "Register Here",
    order_placed: "Order placed successfully!",
    place_order_failed: "Failed to place order",
    fill_required: "Please fill all required fields",
    invalid_credentials: "Invalid credentials",
    logged_in: "Logged in!",
    password: "Password",
    founder_ceo: "Founder & CEO",
    ops_director: "Operations Director",
    head_sourcing: "Head of Sourcing",
    quote_founder: "Our goal is simple: Purity from the soil to your soul.",
    quote_ops: "Ensuring every package delivered carries a promise of quality.",
    quote_sourcing: "I personally visit farms to select only the best for you.",
    tl_title_1: "The Seed is Planted",
    tl_desc_1:
      "Started as a small community initiative to source chemical-free vegetables for friends and family during the pandemic.",
    tl_title_2: "Building Trust",
    tl_desc_2:
      "Expanded to a small warehouse in Badda. We partnered with 50+ local farmers who share our vision of organic farming.",
    tl_title_3: "Swadesh Food Online",
    tl_desc_3:
      "Launched our digital platform to make healthy, organic food accessible to every household in Dhaka.",
    connect_title_1: "Rooted in ",
    connect_title_2: "Trust",
    connect_subtitle:
      "We aren't just a store; we are a family of farmers, dreamers, and doers committed to bringing the pure taste of Bangladesh back to your table.",
    our_mission_tag: "Our Mission",
    mission_title: "Why We Do What We Do",
    mission_p1_start:
      "In a world full of processed options, finding food that heals rather than harms is a challenge. ",
    mission_p1_end:
      "was born out of a necessity—the need for safe, chemical-free, and authentically sourced food.",
    mission_p2:
      "Our mission is to bridge the gap between the hardworking rural farmers of Bangladesh and the urban families who deserve nothing but the best. Every product you receive is a testament to purity, ethics, and care.",
    organic_100: "100% Organic",
    farmer_first: "Farmer First",
    farm_quote: "Directly from the fields of North Bengal.",
    team_title: "Meet the People Behind Swadesh",
    team_subtitle: "Real people, real passion.",
    timeline_title: "Our Journey So Far",
    call_us: "Call Us",
    email_us: "Email Us",
    direct_farm: "Direct from Farm",
    organic: "Organic",
    living: "Living.",
    hero_subtitle:
      "Nourish your family with the purest ingredients. No chemicals, just nature's love.",
    our_story: "Our Story",
    browse_aisles: "Browse Aisles",
    aisles_subtitle: "Everything you need for a healthy kitchen",
    customer_favorites: "Customer Favorites",
    weekly_harvest: "Weekly Harvest",
    view_all: "View All",
    view_all_products: "View All Products",
    just_landed: "Just Landed",
    fresh_arrivals: "Fresh Arrivals",
    fresh_subtitle: "Be the first to taste the season's newest bounty.",
    discover_more: "Discover More",
    trust_p1: "From our soil",
    trust_p2: "to your soul.",
    trust_subtitle:
      "We partner directly with sustainable farmers to bring you produce that is 100% Organic, 100% Swadesh. It's not just food, it's a promise of purity.",
    our_mission: "Our Mission",
    welcome_back: "Welcome Back",
    login_subtitle: "Login to access your account and order history",
    sign_in: "Sign In",
    signing_in: "Signing in...",
    fill_all_fields: "Please fill in all fields",
    login_failed: "Login failed. Please check your credentials.",
    logout_success: "Logged out successfully",
    create_account: "Create Account",
    fresh_in: "Fresh In",
    new_arrivals_title: "New Arrivals",
    new_arrivals_desc:
      "Be the first to explore our latest organic additions. Handpicked for quality and freshness.",
    coming_soon_title: "New products coming soon!",
    restocking_msg:
      "We are restocking our shelves with fresh goods. Check back later.",
    browse_main_store: "Browse Main Store",
    view_more_arrivals: "View More Arrivals",
    change_password: "Change Password",
    order_id: "Order ID",
    details: "Details",
    action: "Action",
    view: "View",
    recipient: "Recipient",
    items_ordered: "Items Ordered",
    cancel_order: "Cancel Order",
    yes_cancel: "Yes, Cancel Order",
    cancel_confirm_msg:
      "Are you sure you want to cancel this order? This action cannot be undone.",
    current_password: "Current Password",
    new_password: "New Password",
    confirm_password: "Confirm New Password",
    update_password: "Update Password",
    order_cancelled: "Order cancelled successfully",
    passwords_mismatch: "Passwords do not match",
    password_updated: "Password updated!",
    join_us: "Join us for authentic and healthy food",
    username: "Username",
    register: "Register",
    creating_account: "Creating Account...",
    already_have_account: "Already have an account?",
    log_in: "Log In",
    reg_failed: "Registration failed. Please try again.",
    search_results: "Search Results",
    searching: "Searching our inventory...",
    no_results: "No products found",
    no_match_1: "We couldn't find anything matching",
    no_match_2: "Try checking for typos or use a more general term.",
    browse_all: "Browse All Products",
    found: "Found",
    new_arrival: "New Arrival",
    only_left: "Only {{count}} left!",
    product_desc_default:
      "Experience the authentic taste of nature with our premium organic selection. Sourced responsibly and delivered fresh to your doorstep.",
    select_size: "Select Size",
    buy_it_now: "Buy It Now",
    delivery: "Delivery",
    delivery_time: "2-3 Days within Dhaka",
    might_like: "You Might Also Like",
    load_more: "Load More",
    added_to_cart: "Added to cart",
    the_store: "The Store",
    collection: "Collection",
    store_desc:
      "Browse our full range of organic, farm-fresh products delivered straight to your door.",
    filter_by: "Filter By",
    size: "Size",
    sort_price: "Sort Price",
    low_to_high: "Low to High",
    high_to_low: "High to Low",
    reset: "Reset",
    no_products_found: "No Products Found",
    adjust_filters: "Try adjusting your filters or search criteria.",
    clear_filters: "Clear All Filters",
    load_more_products: "Load More Products",
    new_badge: "New",
    price_label: "Price",
    add_to_cart: "Add to Cart",
    options: "Options",
    sign_out_confirmation: "Are you sure you want to sign out?",
    quick_links: "Quick Links",
    contact_us: "Contact Us",
    visit_us: "Visit Us",
    all_rights_reserved: "All rights reserved.",
    privacy_policy: "Privacy Policy",
    terms_of_service: "Terms of Service",
    copy_success: "Copied to clipboard",
    copy_fail: "Failed to copy",
    click_to_copy: "Click to copy",
    dark_mode: "Dark Mode",
    light_mode: "Light Mode",
    shipping_cost: "Shipping",
    order_status_new: "New",
    order_status_processing: "Processing",
    order_status_transit: "In Transit",
    order_status_delivered: "Delivered",
    order_status_cancelled: "Cancelled",
    brand_name: "Swadesh Food",
    dashboard_report: "Dashboard_Report",
    out_of_stock: "Out of Stock",
  },
  bn: {
    home: "হোম",
    store: "দোকান",
    new: "নতুন",
    connect: "যোগাযোগ",
    admin: "অ্যাডমিন",
    dashboard: "ড্যাশবোর্ড",
    orders: "অর্ডার তালিকা",
    products: "পণ্যসমূহ",
    categories: "ক্যাটাগরি",
    profile: "প্রোফাইল",
    login: "লগইন",
    logout: "লগআউট",
    search_placeholder: "পণ্য খুঁজুন...",
    back_home: "হোমে ফিরে যান",
    management: "ম্যানেজমেন্ট",
    my_account: "আমার অ্যাকাউন্ট",
    delivery_notice: "আমরা সমগ্র বাংলাদেশে ডেলিভারি করি!",
    brand_tagline: "প্রকৃতির বিশুদ্ধ স্বাদ নিন।",
    category_management: "ক্যাটাগরি ম্যানেজমেন্ট",
    search_categories: "ক্যাটাগরি খুঁজুন...",
    add_category: "নতুন ক্যাটাগরি যোগ করুন",
    category_name: "ক্যাটাগরির নাম",
    actions: "অ্যাকশন",
    edit: "এডিট",
    delete: "মুছুন",
    edit_category: "ক্যাটাগরি এডিট করুন",
    create_category: "নতুন ক্যাটাগরি তৈরি করুন",
    create_category_btn: "ক্যাটাগরি তৈরি করুন",
    update_category: "ক্যাটাগরি আপডেট করুন",
    category_name_label: "ক্যাটাগরির নাম",
    enter_category_name: "অনুগ্রহ করে ক্যাটাগরির নাম দিন",
    category_placeholder: "যেমন: চাল, মসলা, পানীয়",
    cancel: "বাতিল",
    delete_category_title: "ক্যাটাগরি মুছবেন?",
    delete_category_confirm:
      "এটি ফিরিয়ে আনা যাবে না। এই ক্যাটাগরির পণ্যগুলো প্রভাবিত হতে পারে।",
    category_updated: "ক্যাটাগরি সফলভাবে আপডেট করা হয়েছে",
    category_created: "ক্যাটাগরি সফলভাবে তৈরি করা হয়েছে",
    category_deleted: "ক্যাটাগরি মুছে ফেলা হয়েছে",
    load_failed: "ক্যাটাগরি লোড করতে ব্যর্থ হয়েছে",
    update_failed: "আপডেট ব্যর্থ হয়েছে",
    creation_failed: "তৈরি ব্যর্থ হয়েছে",
    delete_failed: "মুছতে ব্যর্থ হয়েছে",
    of: "এর মধ্যে",
    items: "টি আইটেম",
    dashboard_overview: "ড্যাশবোর্ড ওভারভিউ",
    analytics_center: "অ্যানালিটিক্স সেন্টার",
    analytics_desc: "স্টোরের পারফরম্যান্স এবং প্রয়োজনীয় কাজের ওভারভিউ।",
    export: "এক্সপোর্ট",
    revenue: "আয়",
    gross_income: "মোট আয়",
    total_profit: "মোট লাভ",
    net_profit_desc: "আয় - রেসিপি খরচ",
    profit_margin: "লাভের মার্জিন",
    total_processed: "মোট প্রসেস করা হয়েছে",
    revenue_trends: "আয়ের প্রবণতা",
    pending_actions: "অপেক্ষমান কাজ",
    order: "অর্ডার",
    all_caught_up: "সব কাজ শেষ!",
    top_selling_products: "সেরা বিক্রিত পণ্য",
    product: "পণ্য",
    category: "ক্যাটাগরি",
    sold: "বিক্রিত",
    sales_by_category: "ক্যাটাগরি অনুযায়ী বিক্রি",
    peak_order_times: "অর্ডারের পিক টাইম",
    regional_distribution: "আঞ্চলিক বিতরণ",
    sales_history: "বিক্রির ইতিহাস",
    top_products: "সেরা পণ্য",
    order_history: "অর্ডার ইতিহাস",
    filter_by_user: "গ্রাহক অনুযায়ী ফিল্টার",
    payment_status: "পেমেন্ট স্ট্যাটাস",
    refresh: "রিফ্রেশ",
    customer: "গ্রাহক",
    date: "তারিখ",
    status: "অবস্থা",
    status_new: "নতুন",
    status_processing: "প্রক্রিয়াধীন",
    status_transit: "পথে আছে",
    status_delivered: "ডেলিভারি সম্পন্ন",
    payment: "পেমেন্ট",
    paid: "পরিশোধিত",
    unpaid: "অপরিশোধিত",
    marked_paid: "পরিশোধিত হিসেবে চিহ্নিত",
    marked_unpaid: "অপরিশোধিত হিসেবে চিহ্নিত",
    status_updated: "অবস্থা আপডেট করা হয়েছে",
    view_details: "বিস্তারিত দেখুন",
    delete_order_title: "অর্ডার মুছবেন?",
    delete_order_confirm: "এটি ফিরিয়ে আনা যাবে না।",
    order_details: "অর্ডার বিস্তারিত",
    name: "নাম",
    email: "ইমেইল",
    phone: "ফোন",
    address: "ঠিকানা",
    no_notes: "কোনো নোট নেই",
    error_parsing: "পার্সিং ত্রুটি",
    product_inventory: "পণ্যের তালিকা",
    search_products: "পণ্য খুঁজুন...",
    add_product: "পণ্য যোগ করুন",
    image_size_error: "ছবির সাইজ ১এমবি এর কম হতে হবে!",
    load_products_failed: "পণ্য লোড করতে ব্যর্থ হয়েছে",
    select_valid_image: "অনুগ্রহ করে একটি সঠিক ছবি নির্বাচন করুন",
    product_updated: "পণ্য আপডেট করা হয়েছে",
    product_created: "পণ্য তৈরি করা হয়েছে",
    error_saving_product: "পণ্য সংরক্ষণে ত্রুটি",
    delete_product_title: "পণ্য মুছবেন?",
    delete_product_confirm: "এটি ফিরিয়ে আনা যাবে না।",
    deleted_success: "সফলভাবে মুছে ফেলা হয়েছে",
    ingredient_added: "উপাদান যোগ করা হয়েছে",
    select_image_upload: "অনুগ্রহ করে অন্তত একটি নতুন ছবি নির্বাচন করুন",
    gallery_updated: "গ্যালারি সফলভাবে আপডেট করা হয়েছে!",
    upload_failed: "আপলোড ব্যর্থ হয়েছে",
    main_image: "মূল ছবি",
    stock: "স্টক",
    gallery: "গ্যালারি",
    recipe: "রেসিপি",
    edit_product: "পণ্য এডিট করুন",
    new_product: "নতুন পণ্য",
    size_unit: "আকার/ইউনিট",
    size_placeholder: "যেমন: বড়, ৫০০ গ্রাম",
    description: "বিবরণ",
    description_max_error: "বিবরণ ২০০০ অক্ষরের বেশি হতে পারবে না",
    product_details_placeholder: "পণ্যের বিস্তারিত...",
    upload_main_image: "অনুগ্রহ করে পণ্যের মূল ছবি আপলোড করুন",
    select_image_file: "ছবির ফাইল নির্বাচন করুন (সর্বোচ্চ ১এমবি)",
    mark_new_arrival: "নতুন আগমন হিসেবে চিহ্নিত করুন",
    save_product: "পণ্য সংরক্ষণ করুন",
    item_name: "আইটেমের নাম",
    qty: "পরিমাণ",
    cost: "খরচ ($)",
    ingredient: "উপাদান",
    unit_cost: "ইউনিট খরচ",
    total: "মোট",
    upload_images: "ছবি আপলোড করুন",
    side_view: "সাইড ভিউ (ছবি ২)",
    detail_view: "বিস্তারিত ভিউ (ছবি ৩)",
    max_1mb: "সর্বোচ্চ ১এমবি",
    shopping_cart: "শপিং কার্ট",
    you_have: "আপনার আছে",
    items_in_cart: "টি আইটেম কার্টে",
    cart_empty_msg: "আপনার কার্ট বর্তমানে খালি",
    cart_is_empty: "আপনার কার্ট খালি",
    looks_like_empty: "মনে হচ্ছে আপনি এখনও কার্টে কিছু যোগ করেননি।",
    start_shopping: "কেনাকাটা শুরু করুন",
    order_summary: "অর্ডার সারাংশ",
    subtotal: "সর্বমোট",
    shipping: "শিপিং",
    proceed_checkout: "চেকআউটে যান",
    continue_shopping: "আরও কেনাকাটা করুন",
    checkout: "চেকআউট",
    complete_purchase: "আপনার কেনাকাটার তথ্য নিচে দিন।",
    shipping_info: "শিপিং তথ্য",
    full_name: "পুরো নাম",
    email_optional: "ইমেইল (ঐচ্ছিক)",
    phone_number: "ফোন নম্বর",
    full_address: "পুরো ঠিকানা (বাসা, রাস্তা, এলাকা, শহর)",
    order_notes: "অর্ডার নোট (ঐচ্ছিক)",
    payment_method: "পেমেন্ট পদ্ধতি",
    cash_on_delivery: "ক্যাশ অন ডেলিভারি",
    digital_payment: "ডিজিটাল পেমেন্ট",
    coming_soon: "শীঘ্রই আসছে",
    your_order: "আপনার অর্ডার",
    confirm_order: "অর্ডার নিশ্চিত করুন",
    login_required: "লগইন প্রয়োজন",
    login_required_msg: "অর্ডার করতে হলে আপনাকে লগইন করতে হবে।",
    login_continue: "লগইন করুন",
    no_account: "অ্যাকাউন্ট নেই?",
    register_here: "নিবন্ধন করুন",
    order_placed: "অর্ডার সফলভাবে করা হয়েছে!",
    place_order_failed: "অর্ডার করতে ব্যর্থ হয়েছে",
    fill_required: "অনুগ্রহ করে সব প্রয়োজনীয় তথ্য দিন",
    invalid_credentials: "ভুল তথ্য দেওয়া হয়েছে",
    logged_in: "লগইন সফল!",
    password: "পাসওয়ার্ড",
    founder_ceo: "প্রতিষ্ঠাতা ও সিইও",
    ops_director: "অপারেশন ডিরেক্টর",
    head_sourcing: "হেড অফ সোর্সিং",
    quote_founder:
      "আমাদের লক্ষ্য সহজ: মাটি থেকে আপনার আত্মা পর্যন্ত বিশুদ্ধতা।",
    quote_ops: "প্রতিটি ডেলিভারি যেন গুণের প্রতিশ্রুতি বহন করে তা নিশ্চিত করা।",
    quote_sourcing:
      "আমি ব্যক্তিগতভাবে খামারগুলো পরিদর্শন করি শুধু সেরা পণ্যটি বেছে নেওয়ার জন্য।",
    tl_title_1: "বীজ বপন",
    tl_desc_1:
      "মহামারীর সময় পরিবার ও বন্ধুদের জন্য রাসায়নিক মুক্ত শাকসবজি সংগ্রহের একটি ছোট উদ্যোগ হিসেবে শুরু হয়েছিল।",
    tl_title_2: "বিশ্বাস অর্জন",
    tl_desc_2:
      "বাড্ডায় একটি ছোট গুদামে সম্প্রসারণ। অর্গানিক চাষের স্বপ্ন দেখে এমন ৫০+ কৃষকের সাথে আমরা যুক্ত হই।",
    tl_title_3: "স্বদেশ ফুড অনলাইন",
    tl_desc_3:
      "ঢাকার প্রতিটি ঘরে স্বাস্থ্যকর ও অর্গানিক খাবার পৌঁছে দিতে আমাদের ডিজিটাল প্ল্যাটফর্ম চালু করি।",
    connect_title_1: "আমাদের মূল ভিত্তি ",
    connect_title_2: "বিশ্বাস",
    connect_subtitle:
      "আমরা শুধু একটি দোকান নই; আমরা কৃষক, স্বপ্নদর্শী এবং কর্মীদের একটি পরিবার যারা বাংলাদেশের খাঁটি স্বাদ আপনার টেবিলে ফিরিয়ে আনতে প্রতিশ্রুতিবদ্ধ।",
    our_mission_tag: "আমাদের লক্ষ্য",
    mission_title: "আমরা কেন এই কাজটি করি",
    mission_p1_start:
      "প্রক্রিয়াজাত খাবারের এই যুগে, ক্ষতিকর নয় বরং নিরাময়কারী খাবার খুঁজে পাওয়া একটি চ্যালেঞ্জ। নিরাপদ, রাসায়নিক-মুক্ত এবং খাঁটি খাবারের প্রয়োজন থেকেই ",
    mission_p1_end: "-এর জন্ম।",
    mission_p2:
      "আমাদের লক্ষ্য হলো বাংলাদেশের কঠোর পরিশ্রমী গ্রামীণ কৃষক এবং শহুরে পরিবারগুলোর মধ্যে সেতুবন্ধন তৈরি করা, যারা সেরা কিছুর দাবিদার। আপনার হাতে পৌঁছানো প্রতিটি পণ্য বিশুদ্ধতা, নৈতিকতা এবং যত্নের প্রমাণ।",
    organic_100: "১০০% অর্গানিক",
    farmer_first: "কৃষক প্রথম",
    farm_quote: "সরাসরি উত্তরবঙ্গের মাঠ থেকে।",
    team_title: "স্বদেশের পেছনের কারিগরদের চিনুন",
    team_subtitle: "আসল মানুষ, আসল আবেগ।",
    timeline_title: "আমাদের এ পর্যন্ত পথচলা",
    call_us: "কল করুন",
    email_us: "ইমেইল করুন",
    direct_farm: "সরাসরি খামার থেকে",
    organic: "অর্গানিক",
    living: "জীবন।",
    hero_subtitle:
      "সবচেয়ে বিশুদ্ধ উপকরণ দিয়ে আপনার পরিবারকে পুষ্ট করুন। কোনো রাসায়নিক নয়, শুধু প্রকৃতির ভালোবাসা।",
    our_story: "আমাদের গল্প",
    browse_aisles: "পণ্য ব্রাউজ করুন",
    aisles_subtitle: "একটি স্বাস্থ্যকর রান্নাঘরের জন্য আপনার যা কিছু প্রয়োজন",
    customer_favorites: "গ্রাহকদের পছন্দের",
    weekly_harvest: "সাপ্তাহিক সংগ্রহ",
    view_all: "সব দেখুন",
    view_all_products: "সব পণ্য দেখুন",
    just_landed: "সদ্য আগত",
    fresh_arrivals: "টাটকা পণ্য",
    fresh_subtitle: "মৌসুমের নতুন ফসলের স্বাদ সবার আগে নিন।",
    discover_more: "আরও জানুন",
    trust_p1: "আমাদের মাটি থেকে",
    trust_p2: "আপনার আত্মা পর্যন্ত।",
    trust_subtitle:
      "আমরা টেকসই কৃষকদের সাথে সরাসরি কাজ করি যাতে আপনাকে ১০০% অর্গানিক, ১০০% স্বদেশি পণ্য দিতে পারি। এটি শুধু খাবার নয়, এটি বিশুদ্ধতার প্রতিশ্রুতি।",
    our_mission: "আমাদের লক্ষ্য",
    welcome_back: "স্বাগতম",
    login_subtitle: "আপনার অ্যাকাউন্ট এবং অর্ডার দেখতে লগইন করুন",
    sign_in: "লগইন",
    signing_in: "লগইন হচ্ছে...",
    fill_all_fields: "অনুগ্রহ করে সব তথ্য দিন",
    login_failed: "লগইন ব্যর্থ হয়েছে। দয়া করে আপনার তথ্য যাচাই করুন।",
    logout_success: "সফলভাবে লগআউট হয়েছে",
    create_account: "অ্যাকাউন্ট তৈরি করুন",
    fresh_in: "সদ্য আগত",
    new_arrivals_title: "নতুন সংগ্রহ",
    new_arrivals_desc:
      "আমাদের সর্বশেষ অর্গানিক পণ্যগুলো সবার আগে দেখুন। গুণমান এবং সতেজতার জন্য বাছাই করা।",
    coming_soon_title: "নতুন পণ্য শীঘ্রই আসছে!",
    restocking_msg:
      "আমরা আমাদের তাকগুলোতে নতুন পণ্য সাজাচ্ছি। কিছুক্ষণ পর আবার চেক করুন।",
    browse_main_store: "মূল দোকান ব্রাউজ করুন",
    view_more_arrivals: "আরও নতুন পণ্য দেখুন",
    change_password: "পাসওয়ার্ড পরিবর্তন",
    order_id: "অর্ডার আইডি",
    details: "বিস্তারিত",
    action: "অ্যাকশন",
    view: "দেখুন",
    recipient: "প্রাপক",
    items_ordered: "অর্ডার করা পণ্য",
    cancel_order: "অর্ডার বাতিল",
    yes_cancel: "হ্যাঁ, বাতিল করুন",
    cancel_confirm_msg:
      "আপনি কি নিশ্চিত যে আপনি এই অর্ডারটি বাতিল করতে চান? এটি ফিরিয়ে আনা যাবে না।",
    current_password: "বর্তমান পাসওয়ার্ড",
    new_password: "নতুন পাসওয়ার্ড",
    confirm_password: "নতুন পাসওয়ার্ড নিশ্চিত করুন",
    update_password: "পাসওয়ার্ড আপডেট করুন",
    order_cancelled: "অর্ডার সফলভাবে বাতিল করা হয়েছে",
    passwords_mismatch: "পাসওয়ার্ড মিলছে না",
    password_updated: "পাসওয়ার্ড আপডেট হয়েছে!",
    join_us: "খাঁটি এবং স্বাস্থ্যকর খাবারের জন্য আমাদের সাথে যোগ দিন",
    username: "ব্যবহারকারীর নাম",
    register: "নিবন্ধন করুন",
    creating_account: "অ্যাকাউন্ট তৈরি হচ্ছে...",
    already_have_account: "ইতিমধ্যে একটি অ্যাকাউন্ট আছে?",
    log_in: "লগইন",
    reg_failed: "নিবন্ধন ব্যর্থ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
    search_results: "অনুসন্ধানের ফলাফল",
    searching: "পণ্য খোঁজা হচ্ছে...",
    no_results: "কোনো পণ্য পাওয়া যায়নি",
    no_match_1: "আমরা এর সাথে মিল রেখে কিছু খুঁজে পাইনি",
    no_match_2: "বানান চেক করুন বা আরও সাধারণ শব্দ ব্যবহার করুন।",
    browse_all: "সব পণ্য দেখুন",
    found: "পাওয়া গেছে",
    new_arrival: "নতুন আগমন",
    only_left: "মাত্র {{count}}টি বাকি!",
    product_desc_default:
      "আমাদের প্রিমিয়াম অর্গানিক নির্বাচনের সাথে প্রকৃতির আসল স্বাদ অনুভব করুন। দায়িত্বশীলভাবে সংগ্রহ করা এবং আপনার দোরগোড়ায় তাজা পৌঁছে দেওয়া হয়।",
    select_size: "আকার নির্বাচন করুন",
    buy_it_now: "এখনই কিনুন",
    delivery: "ডেলিভারি",
    delivery_time: "ঢাকা সিটির মধ্যে ২-৩ দিন",
    might_like: "আপনার পছন্দ হতে পারে",
    load_more: "আরও দেখুন",
    added_to_cart: "কার্টে যোগ করা হয়েছে",
    the_store: "দোকান",
    collection: "সংগ্রহ",
    store_desc:
      "আমাদের অর্গানিক এবং তাজা পণ্যের সম্পূর্ণ তালিকা দেখুন যা সরাসরি আপনার দরজায় পৌঁছে দেওয়া হয়।",
    filter_by: "ফিল্টার",
    size: "আকার",
    sort_price: "মূল্য অনুসারে",
    low_to_high: "কম থেকে বেশি",
    high_to_low: "বেশি থেকে কম",
    reset: "রিসেট",
    no_products_found: "কোনো পণ্য পাওয়া যায়নি",
    adjust_filters:
      "আপনার ফিল্টার বা অনুসন্ধানের শব্দ পরিবর্তন করার চেষ্টা করুন।",
    clear_filters: "সব ফিল্টার মুছুন",
    load_more_products: "আরও পণ্য দেখুন",
    new_badge: "নতুন",
    price_label: "দাম",
    add_to_cart: "কার্টে যোগ করুন",
    options: "বাছাই করুন",
    sign_out_confirmation: "আপনি কি নিশ্চিত যে আপনি সাইন আউট করতে চান?",
    quick_links: "কুইক লিঙ্কস",
    contact_us: "কন্টাক্ট করুন",
    visit_us: "আমাদের ঠিকানা",
    all_rights_reserved: "সব অধিকার সংরক্ষিত।",
    privacy_policy: "প্রাইভেসি পলিসি",
    terms_of_service: "টার্মস অফ সার্ভিস",
    copy_success: "কপি হয়েছে!",
    copy_fail: "কপি করা যায়নি",
    click_to_copy: "কপি করতে ক্লিক করুন",
    dark_mode: "ডার্ক মোড",
    light_mode: "লাইট মোড",
    shipping_cost: "শিপিং চার্জ",
    order_status_new: "নতুন",
    order_status_processing: "প্রসেসিং",
    order_status_transit: "ইন ট্রানজিট",
    order_status_delivered: "ডেলিভারড",
    order_status_cancelled: "বাতিল",
    brand_name: "স্বদেশ ফুড",
    dashboard_report: "ড্যাশবোর্ড_রিপোর্ট",
    out_of_stock: "স্টক নেই",
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(
    localStorage.getItem("lang") || "en",
  );

  const switchLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem("lang", lang);
  };

  // Helper to get text
  const t = (key, params = {}) => {
    let text = translations[language][key] || key;

    // Simple interpolation for {{key}}
    Object.keys(params).forEach((paramKey) => {
      text = text.replace(`{{${paramKey}}}`, params[paramKey]);
    });

    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, switchLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

LanguageProvider.propTypes = {
  children: PropTypes.node,
};

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => useContext(LanguageContext);
