import { createContext, useContext, useState } from "react";
import PropTypes from "prop-types";

const LanguageContext = createContext();

// Dictionary
const translations = {
  en: {
    home: "Home",
    store: "Store",
    new: "New",
    connect: "Connect",
    admin: "Admin",
    dashboard: "Dashboard",
    orders: "Orders",
    products: "Products",
    categories: "Categories",
    profile: "Profile",
    login: "Login",
    logout: "Logout",
    search_placeholder: "Search essentials...",
    back_home: "Back to Home",
    management: "Management",
    my_account: "My Account",
    delivery_notice: "We deliver across Bangladesh!",
    brand_tagline: "Taste the Purity of Nature.",
    category_management: "Category Management",
    search_categories: "Search categories...",
    add_category: "Add New Category",
    category_name: "Category Name",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    edit_category: "Edit Category",
    create_category: "Create New Category",
    create_category_btn: "Create Category",
    update_category: "Update Category",
    category_name_label: "Category Name",
    enter_category_name: "Please enter a category name",
    category_placeholder: "e.g. Rice, Spices, Beverages",
    cancel: "Cancel",
    delete_category_title: "Delete Category?",
    delete_category_confirm:
      "This action cannot be undone. Products in this category might be affected.",
    category_updated: "Category updated successfully",
    category_created: "Category created successfully",
    category_deleted: "Category deleted",
    load_failed: "Failed to load categories",
    update_failed: "Update failed",
    creation_failed: "Creation failed",
    delete_failed: "Delete failed",
    of: "of",
    items: "items",
    dashboard_overview: "Dashboard Overview",
    analytics_center: "Analytics Center",
    analytics_desc: "Overview of store performance and required actions.",
    export: "Export",
    revenue: "Revenue",
    gross_income: "Gross income",
    total_profit: "Total Profit",
    net_profit_desc: "Revenue - Recipe Costs",
    profit_margin: "Profit Margin",
    total_processed: "Total processed",
    revenue_trends: "Revenue Trends",
    pending_actions: "Pending Actions",
    order: "Order",
    all_caught_up: "All caught up!",
    top_selling_products: "Top Selling Products",
    product: "Product",
    category: "Category",
    sold: "Sold",
    sales_by_category: "Sales by Category",
    peak_order_times: "Peak Order Times",
    regional_distribution: "Regional Distribution",
    sales_history: "Sales History",
    top_products: "Top Products",
    order_history: "Order History",
    filter_by_user: "Filter by User",
    payment_status: "Payment Status",
    refresh: "Refresh",
    customer: "Customer",
    date: "Date",
    status: "Status",
    status_new: "New",
    status_processing: "Processing",
    status_transit: "In Transit",
    status_delivered: "Delivered",
    payment: "Payment",
    paid: "Paid",
    unpaid: "Unpaid",
    marked_paid: "Marked as Paid",
    marked_unpaid: "Marked as Unpaid",
    status_updated: "Status Updated",
    view_details: "View Details",
    delete_order_title: "Delete Order?",
    delete_order_confirm: "This action cannot be undone.",
    order_details: "Order Details",
    name: "Name",
    email: "Email",
    phone: "Phone",
    address: "Address",
    no_notes: "No notes",
    error_parsing: "Error parsing",
    product_inventory: "Product Inventory",
    search_products: "Search products...",
    add_product: "Add Product",
    image_size_error: "Image must be smaller than 1MB!",
    load_products_failed: "Failed to load products",
    select_valid_image: "Please select a valid image file",
    product_updated: "Product Updated",
    product_created: "Product Created",
    error_saving_product: "Error saving product",
    delete_product_title: "Delete Product?",
    delete_product_confirm: "This cannot be undone.",
    deleted_success: "Deleted successfully",
    ingredient_added: "Ingredient added",
    select_image_upload: "Please select at least one new image to upload",
    gallery_updated: "Gallery updated successfully!",
    upload_failed: "Upload failed",
    main_image: "Main Image",
    stock: "Stock",
    gallery: "Gallery",
    recipe: "Recipe",
    edit_product: "Edit Product",
    new_product: "New Product",
    size_unit: "Size/Unit",
    size_placeholder: "e.g. Large, 500g",
    description: "Description",
    description_max_error: "Description cannot exceed 2000 characters",
    product_details_placeholder: "Product details...",
    upload_main_image: "Please upload the main product image",
    select_image_file: "Select Image File (Max 1MB)",
    mark_new_arrival: "Mark as New Arrival",
    save_product: "Save Product",
    item_name: "Item Name",
    qty: "Qty",
    cost: "Cost ($)",
    ingredient: "Ingredient",
    unit_cost: "Unit Cost",
    total: "Total",
    upload_images: "Upload Images",
    side_view: "Side View (Image 2)",
    detail_view: "Detail View (Image 3)",
    max_1mb: "Max 1MB",
    shopping_cart: "Shopping Cart",
    you_have: "You have",
    items_in_cart: "items in your cart",
    cart_empty_msg: "Your cart is currently empty",
    cart_is_empty: "Your cart is empty",
    looks_like_empty: "Looks like you haven't added anything to your cart yet.",
    start_shopping: "Start Shopping",
    order_summary: "Order Summary",
    subtotal: "Subtotal",
    shipping: "Shipping",
    proceed_checkout: "Proceed to Checkout",
    continue_shopping: "Continue Shopping",
    checkout: "Checkout",
    complete_purchase: "Complete your purchase details below.",
    shipping_info: "Shipping Information",
    full_name: "Full Name",
    email_optional: "Email (Optional)",
    phone_number: "Phone Number",
    full_address: "Full Address (House, Street, Area, City)",
    order_notes: "Order notes (Optional)",
    payment_method: "Payment Method",
    cash_on_delivery: "Cash on Delivery",
    digital_payment: "Digital Payment",
    coming_soon: "Coming Soon",
    your_order: "Your Order",
    confirm_order: "Confirm Order",
    login_required: "Login Required",
    login_required_msg: "You need to log in to place an order.",
    login_continue: "Login & Continue",
    no_account: "Don't have an account?",
    register_here: "Register Here",
    order_placed: "Order placed successfully!",
    place_order_failed: "Failed to place order",
    fill_required: "Please fill all required fields",
    invalid_credentials: "Invalid credentials",
    logged_in: "Logged in!",
    password: "Password",
    founder_ceo: "Founder & CEO",
    ops_director: "Operations Director",
    head_sourcing: "Head of Sourcing",
    quote_founder: "Our goal is simple: Purity from the soil to your soul.",
    quote_ops: "Ensuring every package delivered carries a promise of quality.",
    quote_sourcing: "I personally visit farms to select only the best for you.",
    tl_title_1: "The Seed is Planted",
    tl_desc_1:
      "Started as a small community initiative to source chemical-free vegetables for friends and family during the pandemic.",
    tl_title_2: "Building Trust",
    tl_desc_2:
      "Expanded to a small warehouse in Badda. We partnered with 50+ local farmers who share our vision of organic farming.",
    tl_title_3: "Swadesh Food Online",
    tl_desc_3:
      "Launched our digital platform to make healthy, organic food accessible to every household in Dhaka.",
    connect_title_1: "Rooted in ",
    connect_title_2: "Trust",
    connect_subtitle:
      "We aren't just a store; we are a family of farmers, dreamers, and doers committed to bringing the pure taste of Bangladesh back to your table.",
    our_mission_tag: "Our Mission",
    mission_title: "Why We Do What We Do",
    mission_p1_start:
      "In a world full of processed options, finding food that heals rather than harms is a challenge. ",
    mission_p1_end:
      "was born out of a necessity—the need for safe, chemical-free, and authentically sourced food.",
    mission_p2:
      "Our mission is to bridge the gap between the hardworking rural farmers of Bangladesh and the urban families who deserve nothing but the best. Every product you receive is a testament to purity, ethics, and care.",
    organic_100: "100% Organic",
    farmer_first: "Farmer First",
    farm_quote: "Directly from the fields of North Bengal.",
    team_title: "Meet the People Behind Swadesh",
    team_subtitle: "Real people, real passion.",
    timeline_title: "Our Journey So Far",
    call_us: "Call Us",
    email_us: "Email Us",
    direct_farm: "Direct from Farm",
    organic: "Organic",
    living: "Living.",
    hero_subtitle:
      "Nourish your family with the purest ingredients. No chemicals, just nature's love.",
    our_story: "Our Story",
    browse_aisles: "Browse Aisles",
    aisles_subtitle: "Everything you need for a healthy kitchen",
    customer_favorites: "Customer Favorites",
    weekly_harvest: "Weekly Harvest",
    view_all: "View All",
    view_all_products: "View All Products",
    just_landed: "Just Landed",
    fresh_arrivals: "Fresh Arrivals",
    fresh_subtitle: "Be the first to taste the season's newest bounty.",
    discover_more: "Discover More",
    trust_p1: "From our soil",
    trust_p2: "to your soul.",
    trust_subtitle:
      "We partner directly with sustainable farmers to bring you produce that is 100% Organic, 100% Swadesh. It's not just food, it's a promise of purity.",
    our_mission: "Our Mission",
    welcome_back: "Welcome Back",
    login_subtitle: "Login to access your account and order history",
    sign_in: "Sign In",
    signing_in: "Signing in...",
    fill_all_fields: "Please fill in all fields",
    login_failed: "Login failed. Please check your credentials.",
    logout_success: "Logged out successfully",
    create_account: "Create Account",
    fresh_in: "Fresh In",
    new_arrivals_title: "New Arrivals",
    new_arrivals_desc:
      "Be the first to explore our latest organic additions. Handpicked for quality and freshness.",
    coming_soon_title: "New products coming soon!",
    restocking_msg:
      "We are restocking our shelves with fresh goods. Check back later.",
    browse_main_store: "Browse Main Store",
    view_more_arrivals: "View More Arrivals",
    change_password: "Change Password",
    order_id: "Order ID",
    details: "Details",
    action: "Action",
    view: "View",
    recipient: "Recipient",
    items_ordered: "Items Ordered",
    cancel_order: "Cancel Order",
    yes_cancel: "Yes, Cancel Order",
    cancel_confirm_msg:
      "Are you sure you want to cancel this order? This action cannot be undone.",
    current_password: "Current Password",
    new_password: "New Password",
    confirm_password: "Confirm New Password",
    update_password: "Update Password",
    order_cancelled: "Order cancelled successfully",
    passwords_mismatch: "Passwords do not match",
    password_updated: "Password updated!",
    join_us: "Join us for authentic and healthy food",
    username: "Username",
    register: "Register",
    creating_account: "Creating Account...",
    already_have_account: "Already have an account?",
    log_in: "Log In",
    reg_failed: "Registration failed. Please try again.",
    search_results: "Search Results",
    searching: "Searching our inventory...",
    no_results: "No products found",
    no_match_1: "We couldn't find anything matching",
    no_match_2: "Try checking for typos or use a more general term.",
    browse_all: "Browse All Products",
    found: "Found",
    new_arrival: "New Arrival",
    only_left: "Only {{count}} left!",
    product_desc_default:
      "Experience the authentic taste of nature with our premium organic selection. Sourced responsibly and delivered fresh to your doorstep.",
    select_size: "Select Size",
    buy_it_now: "Buy It Now",
    delivery: "Delivery",
    delivery_time: "2-3 Days within Dhaka",
    might_like: "You Might Also Like",
    load_more: "Load More",
    added_to_cart: "Added to cart",
    the_store: "The Store",
    collection: "Collection",
    store_desc:
      "Browse our full range of organic, farm-fresh products delivered straight to your door.",
    filter_by: "Filter By",
    size: "Size",
    sort_price: "Sort Price",
    low_to_high: "Low to High",
    high_to_low: "High to Low",
    reset: "Reset",
    no_products_found: "No Products Found",
    adjust_filters: "Try adjusting your filters or search criteria.",
    clear_filters: "Clear All Filters",
    load_more_products: "Load More Products",
    new_badge: "New",
    price_label: "Price",
    add_to_cart: "Add to Cart",
    options: "Options",
    sign_out_confirmation: "Are you sure you want to sign out?",
    quick_links: "Quick Links",
    contact_us: "Contact Us",
    visit_us: "Visit Us",
    all_rights_reserved: "All rights reserved.",
    privacy_policy: "Privacy Policy",
    terms_of_service: "Terms of Service",
    copy_success: "Copied to clipboard",
    copy_fail: "Failed to copy",
    click_to_copy: "Click to copy",
    dark_mode: "Dark Mode",
    light_mode: "Light Mode",
    shipping_cost: "Shipping",
    order_status_new: "New",
    order_status_processing: "Processing",
    order_status_transit: "In Transit",
    order_status_delivered: "Delivered",
    order_status_cancelled: "Cancelled",
    brand_name: "Swadesh Food",
    dashboard_report: "Dashboard_Report",
    out_of_stock: "Out of Stock",
  },
  bn: {
    home: "হোম",
    store: "স্টোর",
    new: "নতুন",
    connect: "কানেক্ট",
    admin: "অ্যাডমিন",
    dashboard: "ড্যাশবোর্ড",
    orders: "অর্ডারস",
    products: "প্রোডাক্টস",
    categories: "ক্যাটাগরি",
    profile: "প্রোফাইল",
    login: "লগইন",
    logout: "লগআউট",
    search_placeholder: "সার্চ করুন...",
    back_home: "ব্যাক টু হোম",
    management: "ম্যানেজমেন্ট",
    my_account: "আমার অ্যাকাউন্ট",
    delivery_notice: "সারা বাংলাদেশে ডেলিভারি দিচ্ছি!",
    brand_tagline: "প্রকৃতির খাঁটি স্বাদ।",
    category_management: "ক্যাটাগরি ম্যানেজমেন্ট",
    search_categories: "ক্যাটাগরি সার্চ করুন...",
    add_category: "নতুন ক্যাটাগরি অ্যাড করুন",
    category_name: "ক্যাটাগরির নাম",
    actions: "অ্যাকশন",
    edit: "এডিট",
    delete: "ডিলিট",
    edit_category: "ক্যাটাগরি এডিট",
    create_category: "নতুন ক্যাটাগরি তৈরি করুন",
    create_category_btn: "ক্যাটাগরি ক্রিয়েট করুন",
    update_category: "ক্যাটাগরি আপডেট",
    category_name_label: "ক্যাটাগরির নাম",
    enter_category_name: "ক্যাটাগরির নাম লিখুন",
    category_placeholder: "যেমন: চাল, মসলা, ড্রিঙ্কস",
    cancel: "ক্যান্সেল",
    delete_category_title: "ক্যাটাগরি ডিলিট করবেন?",
    delete_category_confirm:
      "এটি আনডু করা যাবে না। এই ক্যাটাগরির প্রোডাক্টগুলো এফেক্টেড হতে পারে।",
    category_updated: "ক্যাটাগরি সফলভাবে আপডেট হয়েছে",
    category_created: "ক্যাটাগরি সফলভাবে ক্রিয়েট হয়েছে",
    category_deleted: "ক্যাটাগরি ডিলিট করা হয়েছে",
    load_failed: "লোড করতে প্রবলেম হয়েছে",
    update_failed: "আপডেট ফেইলড",
    creation_failed: "ক্রিয়েট করা যায়নি",
    delete_failed: "ডিলিট করা যায়নি",
    of: "এর মধ্যে",
    items: "টি আইটেম",
    dashboard_overview: "ড্যাশবোর্ড ওভারভিউ",
    analytics_center: "অ্যানালিটিক্স সেন্টার",
    analytics_desc: "স্টোরের পারফরম্যান্স এবং প্রয়োজনীয় কাজের ডিটেইলস।",
    export: "এক্সপোর্ট",
    revenue: "রেভিনিউ",
    gross_income: "মোট ইনকাম",
    total_profit: "টোটাল প্রফিট",
    net_profit_desc: "রেভিনিউ - রেসিপি কস্ট",
    profit_margin: "প্রফিট মার্জিন",
    total_processed: "মোট প্রসেস করা হয়েছে",
    revenue_trends: "রেভিনিউ ট্রেন্ডস",
    pending_actions: "পেন্ডিং কাজ",
    order: "অর্ডার",
    all_caught_up: "সব কাজ শেষ!",
    top_selling_products: "বেস্ট সেলিং প্রোডাক্টস",
    product: "প্রোডাক্ট",
    category: "ক্যাটাগরি",
    sold: "বিক্রি হয়েছে",
    sales_by_category: "ক্যাটাগরি অনুযায়ী সেলস",
    peak_order_times: "অর্ডারের পিক টাইম",
    regional_distribution: "আঞ্চলিক ডিস্ট্রিবিউশন",
    sales_history: "সেলস হিস্ট্রি",
    top_products: "টপ প্রোডাক্টস",
    order_history: "অর্ডার হিস্ট্রি",
    filter_by_user: "ইউজার অনুযায়ী ফিল্টার",
    payment_status: "পেমেন্ট স্ট্যাটাস",
    refresh: "রিফ্রেশ",
    customer: "কাস্টমার",
    date: "তারিখ",
    status: "স্ট্যাটাস",
    status_new: "নতুন",
    status_processing: "প্রসেসিং",
    status_transit: "ইন ট্রানজিট",
    status_delivered: "ডেলিভারড",
    payment: "পেমেন্ট",
    paid: "পেইড",
    unpaid: "আনপেইড",
    marked_paid: "পেইড হিসেবে মার্ক করা হয়েছে",
    marked_unpaid: "আনপেইড হিসেবে মার্ক করা হয়েছে",
    status_updated: "স্ট্যাটাস আপডেট হয়েছে",
    view_details: "ডিটেইলস দেখুন",
    delete_order_title: "অর্ডার ডিলিট করবেন?",
    delete_order_confirm: "এটি আনডু করা যাবে না।",
    order_details: "অর্ডারের ডিটেইলস",
    name: "নাম",
    email: "ইমেইল",
    phone: "ফোন",
    address: "ঠিকানা",
    no_notes: "কোনো নোট নেই",
    error_parsing: "পার্সিং এরর",
    product_inventory: "প্রোডাক্ট ইনভেন্টরি",
    search_products: "প্রোডাক্ট সার্চ করুন...",
    add_product: "প্রোডাক্ট অ্যাড করুন",
    image_size_error: "ইমেজ ১এমবি এর ছোট হতে হবে!",
    load_products_failed: "প্রোডাক্ট লোড হয়নি",
    select_valid_image: "সঠিক ইমেজ সিলেক্ট করুন",
    product_updated: "প্রোডাক্ট আপডেট হয়েছে",
    product_created: "প্রোডাক্ট ক্রিয়েট হয়েছে",
    error_saving_product: "প্রোডাক্ট সেভ করতে এরর হয়েছে",
    delete_product_title: "প্রোডাক্ট ডিলিট করবেন?",
    delete_product_confirm: "এটি আনডু করা যাবে না।",
    deleted_success: "সফলভাবে ডিলিট হয়েছে",
    ingredient_added: "উপাদান অ্যাড করা হয়েছে",
    select_image_upload: "অন্তত একটি নতুন ইমেজ সিলেক্ট করুন",
    gallery_updated: "গ্যালারি আপডেট হয়েছে!",
    upload_failed: "আপলোড ফেইলড",
    main_image: "মেইন ইমেজ",
    stock: "স্টক",
    gallery: "গ্যালারি",
    recipe: "রেসিপি",
    edit_product: "প্রোডাক্ট এডিট",
    new_product: "নতুন প্রোডাক্ট",
    size_unit: "সাইজ/ইউনিট",
    size_placeholder: "যেমন: ৫ কেজি, ৫০০ গ্রাম",
    description: "বিবরণ",
    description_max_error: "ডেসক্রিপশন ২০০০ অক্ষরের বেশি হবে না",
    product_details_placeholder: "প্রোডাক্ট ডিটেইলস...",
    upload_main_image: "প্রোডাক্টের মেইন ইমেজ আপলোড করুন",
    select_image_file: "ইমেজ ফাইল সিলেক্ট করুন (ম্যাক্স ১এমবি)",
    mark_new_arrival: "নিউ অ্যারাইভাল হিসেবে মার্ক করুন",
    save_product: "প্রোডাক্ট সেভ করুন",
    item_name: "আইটেমের নাম",
    qty: "পরিমাণ",
    cost: "কস্ট ($)",
    ingredient: "উপাদান",
    unit_cost: "ইউনিট কস্ট",
    total: "টোটাল",
    upload_images: "ইমেজ আপলোড",
    side_view: "সাইড ভিউ (ইমেজ ২)",
    detail_view: "ডিটেইল ভিউ (ইমেজ ৩)",
    max_1mb: "ম্যাক্স ১এমবি",
    shopping_cart: "শপিং কার্ট",
    you_have: "আপনার কার্টে",
    items_in_cart: "টি আইটেম আছে",
    cart_empty_msg: "আপনার কার্ট এখন খালি",
    cart_is_empty: "আপনার কার্ট খালি",
    looks_like_empty: "কার্টে এখনও কিছু অ্যাড করেননি।",
    start_shopping: "শপিং শুরু করুন",
    order_summary: "অর্ডার সামারি",
    subtotal: "সাবটোটাল",
    shipping: "শিপিং চার্জ",
    proceed_checkout: "চেকআউট করুন",
    continue_shopping: "আরও শপিং করুন",
    checkout: "চেকআউট",
    complete_purchase: "আপনার ডিটেইলস নিচে দিন।",
    shipping_info: "শিপিং ইনফরমেশন",
    full_name: "পুরো নাম",
    email_optional: "ইমেইল (ঐচ্ছিক)",
    phone_number: "ফোন নম্বর",
    full_address: "পুরো ঠিকানা (বাসা, রোড, শহর)",
    order_notes: "অর্ডার নোট (ঐচ্ছিক)",
    payment_method: "পেমেন্ট মেথড",
    cash_on_delivery: "ক্যাশ অন ডেলিভারি",
    digital_payment: "ডিজিটাল পেমেন্ট",
    coming_soon: "শিগগিরই আসছে",
    your_order: "আপনার অর্ডার",
    confirm_order: "অর্ডার কনফার্ম করুন",
    login_required: "লগইন প্রয়োজন",
    login_required_msg: "অর্ডার করতে হলে লগইন করতে হবে।",
    login_continue: "লগইন করে কন্টিনিউ করুন",
    no_account: "অ্যাকাউন্ট নেই?",
    register_here: "নিবন্ধন করুন",
    order_placed: "অর্ডার সফল হয়েছে!",
    place_order_failed: "অর্ডার প্লেস করা যায়নি",
    fill_required: "সব রিকোয়ার্ড ফিল্ড পূরণ করুন",
    invalid_credentials: "ভুল তথ্য দেওয়া হয়েছে",
    logged_in: "লগইন সফল!",
    password: "পাসওয়ার্ড",
    founder_ceo: "প্রতিষ্ঠাতা ও সিইও",
    ops_director: "অপারেশন ডিরেক্টর",
    head_sourcing: "হেড অফ সোর্সিং",
    quote_founder:
      "আমাদের লক্ষ্য সহজ: মাটি থেকে আপনার আত্মা পর্যন্ত বিশুদ্ধতা।",
    quote_ops: "প্রতিটি ডেলিভারি যেন কোয়ালিটির প্রতিশ্রুতি বহন করে।",
    quote_sourcing: "সেরাটা বেছে নিতে আমি নিজেই খামার ভিজিট করি।",
    tl_title_1: "শুরুটা যখন",
    tl_desc_1:
      "মহামারীর সময় ফ্যামিলি ও ফ্রেন্ডদের জন্য কেমিক্যাল-মুক্ত খাবার সংগ্রহের উদ্যোগ হিসেবে শুরু হয়েছিল।",
    tl_title_2: "বিশ্বাস অর্জন",
    tl_desc_2:
      "বাড্ডায় একটি ছোট ওয়্যারহাউস দিয়ে শুরু। আমাদের অর্গানিক ভিশনে বিশ্বাসী ৫০+ কৃষকের সাথে আমরা কাজ করছি।",
    tl_title_3: "স্বদেশ ফুড অনলাইন",
    tl_desc_3:
      "ঢাকার প্রতিটি ঘরে অর্গানিক ফুড পৌঁছে দিতে আমাদের অনলাইন প্ল্যাটফর্ম চালু হয়েছে।",
    connect_title_1: "ভিত্তি যখন ",
    connect_title_2: "বিশ্বাস",
    connect_subtitle:
      "আমরা শুধু একটি স্টোর নই; আমরা এক পরিবার যারা খাঁটি স্বাদ আপনার টেবিলে পৌঁছে দিতে প্রতিশ্রুতিবদ্ধ।",
    our_mission_tag: "আমাদের মিশন",
    mission_title: "আমরা কেন কাজ করছি",
    mission_p1_start:
      "প্রসেসড খাবারের যুগে, নিরাপদ খাবার খুঁজে পাওয়া চ্যালেঞ্জিং। কেমিক্যাল-মুক্ত এবং খাঁটি খাবারের অভাব মেটাতেই ",
    mission_p1_end: "-এর জন্ম।",
    mission_p2:
      "আমাদের লক্ষ্য হলো গ্রামীণ কৃষক এবং শহুরে ফ্যামিলিগুলোর মধ্যে সেতুবন্ধন তৈরি করা। আমাদের প্রতিটি প্রোডাক্ট বিশুদ্ধতার প্রমাণ।",
    organic_100: "১০০% অর্গানিক",
    farmer_first: "কৃষক প্রথম",
    farm_quote: "সরাসরি উত্তরবঙ্গের মাঠ থেকে।",
    team_title: "স্বদেশের পেছনের কারিগররা",
    team_subtitle: "আমাদের প্যাশন, আপনাদের জন্য।",
    timeline_title: "আমাদের জার্নি",
    call_us: "কল করুন",
    email_us: "ইমেইল করুন",
    direct_farm: "সরাসরি খামার থেকে",
    organic: "অর্গানিক",
    living: "লাইফস্টাইল।",
    hero_subtitle:
      "সবচেয়ে বিশুদ্ধ উপাদান দিয়ে আপনার ফ্যামিলিকে রাখুন হেলদি। কোনো কেমিক্যাল নয়, শুধুই প্রকৃতির ভালোবাসা।",
    our_story: "আমাদের গল্প",
    browse_aisles: "কালেকশন দেখুন",
    aisles_subtitle: "হেলদি কিচেনের জন্য প্রয়োজনীয় সবকিছু",
    customer_favorites: "কাস্টমার ফেভারিট",
    weekly_harvest: "সাপ্তাহিক সংগ্রহ",
    view_all: "সব দেখুন",
    view_all_products: "সব প্রোডাক্টস দেখুন",
    just_landed: "সদ্য আগত",
    fresh_arrivals: "ফ্রেশ অ্যারাইভালস",
    fresh_subtitle: "মৌসুমের নতুন ফসলের স্বাদ সবার আগে নিন।",
    discover_more: "আরও জানুন",
    trust_p1: "মাটি থেকে",
    trust_p2: "আপনার আত্মা পর্যন্ত।",
    trust_subtitle:
      "আমরা সরাসরি কৃষকদের সাথে কাজ করি যাতে আপনি পান ১০০% অর্গানিক ও স্বদেশি প্রোডাক্ট। এটি বিশুদ্ধতার প্রতিশ্রুতি।",
    our_mission: "আমাদের মিশন",
    welcome_back: "স্বাগতম",
    login_subtitle: "আপনার অ্যাকাউন্ট এবং অর্ডার হিস্ট্রি দেখতে লগইন করুন",
    sign_in: "সাইন ইন",
    signing_in: "সাইন ইন হচ্ছে...",
    fill_all_fields: "সবগুলো ফিল্ড পূরণ করুন",
    login_failed: "লগইন হয়নি। দয়া করে সঠিক তথ্য দিন।",
    logout_success: "সফলভাবে লগআউট হয়েছে",
    create_account: "অ্যাকাউন্ট খুলুন",
    fresh_in: "ফ্রেশ ইন",
    new_arrivals_title: "নিউ অ্যারাইভালস",
    new_arrivals_desc:
      "আমাদের লেটেস্ট অর্গানিক অ্যাডিশনগুলো এক্সপ্লোর করুন। সতেজতার গ্যারান্টি।",
    coming_soon_title: "নতুন প্রোডাক্ট শিগগিরই আসছে!",
    restocking_msg: "আমরা শেলফে নতুন স্টক সাজাচ্ছি। কিছুক্ষণ পর আবার চেক করুন।",
    browse_main_store: "মেইন স্টোর দেখুন",
    view_more_arrivals: "আরও প্রোডাক্ট দেখুন",
    change_password: "পাসওয়ার্ড পরিবর্তন",
    order_id: "অর্ডার আইডি",
    details: "ডিটেইলস",
    action: "অ্যাকশন",
    view: "দেখুন",
    recipient: "প্রাপক",
    items_ordered: "অর্ডার করা আইটেম",
    cancel_order: "অর্ডার ক্যান্সেল",
    yes_cancel: "হ্যাঁ, ক্যান্সেল করুন",
    cancel_confirm_msg:
      "আপনি কি নিশ্চিত যে অর্ডারটি ক্যান্সেল করবেন? এটি আনডু করা যাবে না।",
    current_password: "বর্তমান পাসওয়ার্ড",
    new_password: "নতুন পাসওয়ার্ড",
    confirm_password: "পাসওয়ার্ড কনফার্ম করুন",
    update_password: "পাসওয়ার্ড আপডেট করুন",
    order_cancelled: "অর্ডার সফলভাবে ক্যান্সেল হয়েছে",
    passwords_mismatch: "পাসওয়ার্ড ম্যাচ করেনি",
    password_updated: "পাসওয়ার্ড আপডেট হয়েছে!",
    join_us: "খাঁটি ও হেলদি খাবারের জন্য আমাদের সাথে যোগ দিন",
    username: "ইউজারনেম",
    register: "রেজিস্ট্রেশন",
    creating_account: "অ্যাকাউন্ট ক্রিয়েট হচ্ছে...",
    already_have_account: "অলরেডি অ্যাকাউন্ট আছে?",
    log_in: "লগইন",
    reg_failed: "রেজিস্ট্রেশন ফেইলড। আবার ট্রাই করুন।",
    search_results: "সার্চ রেজাল্ট",
    searching: "সার্চ হচ্ছে...",
    no_results: "কোনো প্রোডাক্ট পাওয়া যায়নি",
    no_match_1: "ম্যাচিং কিছু খুঁজে পাওয়া যায়নি",
    no_match_2: "বানান চেক করুন অথবা অন্য শব্দ দিয়ে সার্চ করুন।",
    browse_all: "সব প্রোডাক্ট দেখুন",
    found: "পাওয়া গেছে",
    new_arrival: "নিউ অ্যারাইভাল",
    only_left: "মাত্র {{count}}টি বাকি!",
    product_desc_default:
      "আমাদের প্রিমিয়াম অর্গানিক সিলেকশনের সাথে প্রকৃতির আসল স্বাদ নিন। সতেজতার গ্যারান্টি।",
    select_size: "সাইজ সিলেক্ট করুন",
    buy_it_now: "এখনই কিনুন",
    delivery: "ডেলিভারি",
    delivery_time: "ঢাকার ভেতরে ২-৩ দিন",
    might_like: "আপনার পছন্দ হতে পারে",
    load_more: "লোড মোর",
    added_to_cart: "কার্টে অ্যাড হয়েছে",
    the_store: "স্টোর",
    collection: "কালেকশন",
    store_desc:
      "অর্গানিক ও ফ্রেশ প্রোডাক্টের সম্পূর্ণ রেঞ্জ দেখুন যা সরাসরি আপনার বাসায় পৌঁছে যাবে।",
    filter_by: "ফিল্টার",
    size: "সাইজ",
    sort_price: "প্রাইস অনুযায়ী",
    low_to_high: "কম থেকে বেশি",
    high_to_low: "বেশি থেকে কম",
    reset: "রিসেট",
    no_products_found: "কোনো প্রোডাক্ট পাওয়া যায়নি",
    adjust_filters: "ফিল্টার পরিবর্তন করে ট্রাই করুন।",
    clear_filters: "সব ফিল্টার ক্লিয়ার করুন",
    load_more_products: "আরও প্রোডাক্ট দেখুন",
    new_badge: "নতুন",
    price_label: "প্রাইস",
    add_to_cart: "কার্টে অ্যাড করুন",
    options: "অপশনস",
    sign_out_confirmation: "আপনি কি শিওর যে সাইন আউট করবেন?",
    quick_links: "কুইক লিঙ্কস",
    contact_us: "কন্টাক্ট করুন",
    visit_us: "আমাদের ঠিকানা",
    all_rights_reserved: "অল রাইটস রিজার্ভড।",
    privacy_policy: "প্রাইভেসি পলিসি",
    terms_of_service: "টার্মস অফ সার্ভিস",
    copy_success: "কপি হয়েছে!",
    copy_fail: "কপি করা যায়নি",
    click_to_copy: "কপি করতে ক্লিক করুন",
    dark_mode: "ডার্ক মোড",
    light_mode: "লাইট মোড",
    shipping_cost: "শিপিং চার্জ",
    order_status_new: "নিউ",
    order_status_processing: "প্রসেসিং",
    order_status_transit: "ইন ট্রানজিট",
    order_status_delivered: "ডেলিভারড",
    order_status_cancelled: "ক্যান্সেলড",
    brand_name: "স্বদেশ ফুড",
    dashboard_report: "ড্যাশবোর্ড রিপোর্ট",
    out_of_stock: "স্টক আউট",
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(
    localStorage.getItem("lang") || "en",
  );

  const switchLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem("lang", lang);
  };

  // Helper to get text
  const t = (key, params = {}) => {
    let text = translations[language][key] || key;

    // Simple interpolation for {{key}}
    Object.keys(params).forEach((paramKey) => {
      text = text.replace(`{{${paramKey}}}`, params[paramKey]);
    });

    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, switchLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

LanguageProvider.propTypes = {
  children: PropTypes.node,
};

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => useContext(LanguageContext);
